### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by beew** [Macaulay2/M2#3455] opened 2024-09-04 17:05 UTC
Hi, 

After successfully building M2 I ran the ctests and these tests failed

```

505:normal/command.m2
792:normal/threads.m2
825:goals/ISSAC-97.m2
826:goals/gbZZ.m2
827:goals/joswig.m2
828:quarantine/2-homog-bug.m2
829:quarantine/C05.m2
830:quarantine/HH.m2
831:quarantine/issac-97.m2
832:quarantine/ker8.m2
833:quarantine/lapack.m2
834:quarantine/newlines.m2
836:quarantine/testmulti.m2
842:engine/normal.m2
852:engine/raw-monomial.m2
854:engine/raw-numerics.m2
855:engine/raw-res.m2
856:engine/raw-ring.m2
857:engine/raw-ring2.m2
860:engine/raw-subduction.m2
863:engine/raw.m2
864:engine/raw3.m2
868:engine/test-linalg.m2
871:ComputationsBook/completeIntersections
872:ComputationsBook/constructions
873:ComputationsBook/d-modules
874:ComputationsBook/exterior-algebra
875:ComputationsBook/geometry
876:ComputationsBook/monomialIdeals
877:ComputationsBook/preface
878:ComputationsBook/programming
879:ComputationsBook/schemes
880:ComputationsBook/solving
881:ComputationsBook/toricHilbertScheme
882:ComputationsBook/varieties
```

The test log is attached. 

M2 version is 1.24.05 compiled from source, OS is Ubuntu 22.04

Thanks

[LastTest.log](https://github.com/user-attachments/files/16874375/LastTest.log)

**Comment by mahrud** [comment] 2024-09-04 19:40
Thanks for the reports! I think these are all known and there are several explanations:
```m2
505:normal/command.m2
792:normal/threads.m2
```
These two unfortunately don't work with the ctest setup. See #1706. The important ones to pass are all the other tests in the `normal` directory.
```m2
825:goals/ISSAC-97.m2
826:goals/gbZZ.m2
827:goals/joswig.m2
828:quarantine/2-homog-bug.m2
829:quarantine/C05.m2
830:quarantine/HH.m2
831:quarantine/issac-97.m2
832:quarantine/ker8.m2
833:quarantine/lapack.m2
834:quarantine/newlines.m2
836:quarantine/testmulti.m2
842:engine/normal.m2
852:engine/raw-monomial.m2
854:engine/raw-numerics.m2
855:engine/raw-res.m2
856:engine/raw-ring.m2
857:engine/raw-ring2.m2
860:engine/raw-subduction.m2
863:engine/raw.m2
864:engine/raw3.m2
868:engine/test-linalg.m2
```
These tests unfortunately weren't run for a while and the engine diverged, so the failure is expected. See #1213. 
```m2
871:ComputationsBook/completeIntersections
872:ComputationsBook/constructions
873:ComputationsBook/d-modules
874:ComputationsBook/exterior-algebra
875:ComputationsBook/geometry
876:ComputationsBook/monomialIdeals
877:ComputationsBook/preface
878:ComputationsBook/programming
879:ComputationsBook/schemes
880:ComputationsBook/solving
881:ComputationsBook/toricHilbertScheme
882:ComputationsBook/varieties
```
For these to pass you need to first run `M2-tests-ComputationsBook`. The setup is confusing and not ideal.

**Comment by beew** [comment] 2024-09-05 05:10
@mahrud 

Hi, When to run M2-tests-ComputationsBook?

I ran 

```
 ctest M2-tests-ComputationsBook
```
after 
```
ninja install-packages
```

It ran all the tests and the same tests still failed.

Thanks.

**Comment by mahrud** [comment] 2024-09-05 13:54
I should have clarified, I meant `ninja M2-tests-ComputationsBook`.

**Comment by mahrud** [comment] 2024-10-28 01:14
Closing as duplicate of #1213.

**Closed** 2024-10-28 01:13 UTC
Labels: build issue
