### ISSUE TITLE
get Macaulay2 into Debian

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#286] opened 2015-06-04 13:47 UTC
Doug Torrance dtorrance@monmouthcollege.edu is working on that now, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=439888 and https://groups.google.com/forum/#!topic/macaulay2/jxtKZFRDKDA .

**Comment by d-torrance** [comment] 2015-06-04 16:17
We're currently waiting on a number of build dependencies to make it into Debian before Macaulay2 can be uploaded.  Currently in the NEW queue are singular, frobby, and memtailor.  Once memtailor goes in, we'll upload mathic and then mathicgb.  Packages often sit in the NEW queue for months, so this will take some time.

My packaging work so far can be seen at https://github.com/d-torrance/M2/tree/master.  Currently there's an issue with gmp (See #285).

**Comment by d-torrance** [comment] 2015-06-09 01:48
Dependency update: memtailor has been accepted into Debian unstable.

**Comment by mikestillman** [comment] 2015-06-09 02:12
Great!

**Comment by d-torrance** [comment] 2015-07-08 16:23
Dependency update: mathic has been accepted into Debian unstable.

**Comment by DanGrayson** [comment] 2015-07-08 18:45
Good progress, thanks!

How does one get into "stable"?

**Comment by d-torrance** [comment] 2015-07-08 19:27
Debian packages are first uploaded to "unstable", then migrate to "testing" after a few days (10 in mathic's case).  At some point in the future, "testing" is frozen and becomes the next "stable" release.  Debian just did this recently (Debbie 8, or "jessie", was released in April), so the next release (Debian 9, or "stretch") will probably occur in 2 years or so.

Ubuntu moves much more quickly.  They migrate packages directly from Debian unstable and release every 6 months.  So mathic should be in 15.10 (Wily Werewolf), which will be released in October.

**Comment by dimpase** [comment] 2015-07-10 13:24
I wonder if anyone is involved in updating Fedora M2 packages. It's still version 1.5.

**Comment by DanGrayson** [comment] 2015-07-10 13:54
Maybe Rex Dieter fell behind or stopped?  See
http://www.math.illinois.edu/Macaulay2/Downloads/GNU-Linux/Fedora/index.html

**Comment by rdieter** [comment] 2015-07-10 18:51
Fedora 22 ships Macaulay2-1.6

I've been fighting trying to get more recent versions unsuccessfully.  Will
probably be pinging this group for help/advice sometime soon.

**Comment by d-torrance** [comment] 2015-07-16 17:10
Dependency update: mathicgb has been accepted into Debian unstable.

**Comment by d-torrance** [comment] 2015-07-24 15:08
Dependency update: frobby has been accepted into Debian unstable.

**Comment by DanGrayson** [comment] 2015-07-24 17:49
Thanks!

**Comment by rdieter** [comment] 2015-07-29 17:06
Last I knew, frobby's licensing was nonfree (is why it's not in fedora at
least), has the situation changed?

**Comment by rdieter** [comment] 2015-07-29 17:09
Hrm, looking closer I was mistaken here, sorry for the noise.

**Comment by d-torrance** [comment] 2015-08-26 22:34
Belated dependency update: singular was accepted into Debian unstable on August 3.

At this point, I believe all of the dependencies are now in Debian.

**Comment by DanGrayson** [comment] 2015-08-27 00:32
Thanks!

**Comment by d-torrance** [comment] 2016-04-12 11:57
Status update:

I'm able to successfully build a Debian package using only Debian libraries if I pass --disable-pari to configure and patch out the pari functions giving problems in #396.

Note that this of course breaks these functions which rely on pari, and I don't intend to upload the package until #285 is resolved.  But we're getting closer!

**Comment by DanGrayson** [comment] 2016-04-12 13:08
Thanks, that makes #285 more important.

**Comment by d-torrance** [comment] 2016-04-12 15:30
Also, a question:

`/usr/share/doc/Macaulay2/*/example-output/*.out` and `/usr/lib/Macaulay2/$MACHINE/*/cache/*.db` are installed by default and included in the *.deb packages on the M2 website.

If I'm understanding the code (which I certainly may not be), it looks like these files are intermediate steps in generating the documentation.  Are they still needed after the initial installation?

**Comment by d-torrance** [comment] 2016-04-12 17:18
I just realized these files must be used by the `help` function.

**Comment by DanGrayson** [comment] 2016-04-12 20:16
The *.out files are retained in case someone wants to regenerate the documentation.  The
*.db files allow quick loading of the documentation.

**Comment by d-torrance** [comment] 2016-04-12 22:15
Makes sense.  Thanks for clarifying!

**Comment by d-torrance** [comment] 2016-08-19 13:12
Status update:

The freeze for the next version of Debian (version 9, codename "stretch") is 2017-01-05.  It would be great if M2 could be uploaded by then.  However, #285 is still the big blocker, as we need M2 to build against the Debian gmp package.

I also need to package a few Javascript libraries used by the new Visualize package.

**Comment by d-torrance** [comment] 2017-01-18 15:30
Status update:

I noticed recently that cohomCalg and TOPCOM are now both installed by M2.  I've packaged cohomCalg for Debian, and it was just uploaded to to Debian (currently in the NEW queue pending approval by the FTP masters).  I'll work on TOPCOM next.  I also still need to package the Javascript libraries used by Visualize.

As for M2 itself, it currently won't build using the Debian packages of givaro and fflas-ffpack (both the latest upstream versions), so I'm waiting for #513.  I imagine #285 is still a problem as well, but my builds don't get that far.  :)

**Comment by mikestillman** [comment] 2017-01-18 15:42
I am working on updating M2 to use the newest givaro, ffpack.  The interfaces for these packages appear to have changed quite a bit, and it is taking longer to get it to work.

**Comment by DanGrayson** [comment] 2017-01-18 16:46
Thanks, Doug!

**Comment by alexmyczko** [comment] 2017-12-06 12:56
What's the current state, then?

**Comment by d-torrance** [comment] 2017-12-06 14:03
Thanks for the bump.  I haven't looked at this in a while while I waited #513 and for the latest version of PARI to be uploaded to Debian so that I could implement the fix for #285.  But it looks like both of these things have happened.  :)

I should have some time over the holidays to see where we're at.

**Comment by alexmyczko** [comment] 2018-01-12 12:01
Happy New Year... *the* holidays? Ping...

**Comment by d-torrance** [comment] 2018-01-12 13:57
I did have some time to see where things are at.

After applying a patch to `M2/Macaulay2/d/pari-c.c`, we do get past #285.  (I'll submit a pull request for this in the near future.)

However, then I ran into another problem.  Since we're using the dynamically-linked Debian givaro package and not a statically-linked local copy of givaro, we run into #460.

A new version of givaro was released recently.  I updated the givaro package in Debian, hoping that it might fix things.  But it didn't.  :(

So that's where things stand now.

**Comment by d-torrance** [comment] 2020-05-02 16:22
Time for an update.  With the changes coming in #1096, I'm hopeful that a Debian Macaulay2 package might be around the corner!

I have a draft package that builds based on that branch, but there are some issues:

* mpsolve isn't in Debian yet, so `roots` doesn't work.  I'm working on getting it packaged (https://bugs.debian.org/958919), so this should be resolved soon.
* Building the documentation for `factor` fails.  Based on the discussion in #1096, it looks like flint might be to blame here.

**Comment by DanGrayson** [comment] 2020-05-02 17:18
Thanks.  M2 on the eigen branch seems to start up with double the virtual memory in use.  We're going to have to figure out why.

**Comment by DanGrayson** [comment] 2020-05-17 12:45
Doug, thanks for working on this!

**Comment by d-torrance** [comment] 2020-05-17 18:38
If anyone is interested, my packaging work so far is at:
https://salsa.debian.org/science-team/macaulay2

I'm keeping track of what still needs to be done at:
https://salsa.debian.org/science-team/macaulay2/-/blob/master/debian/TODO.md

**Comment by DanGrayson** [comment] 2020-05-17 19:23
Thanks!

Just the other day I complained to our audience that the top directory in our repository seemed to have no use.  But you have found a use.

How does a file such as debian/macaulay2-common.doc-base get updated when we add a package?

If our configure script build process is deprecated in favor of cmake, can you cope?

**Comment by d-torrance** [comment] 2020-05-17 19:30
I should be able to use wildcards for the .info files, just like the .html ones, for doc-base.  I haven't touched that file in 4 years, so it's very out of date!

cmake should be fine.  debhelper is set up to deal with most common build systems out of the box.  I'd just need to switch any patches of `configure.ac` over to `CMakeLists.txt`.

**Comment by DanGrayson** [comment] 2020-05-17 19:41
Is it the custom for downstream debian package building files ever to get incorporated upstream?

**Comment by d-torrance** [comment] 2020-05-17 19:46
It's not very common, but it's not unheard of.  Of the various packages I help maintain in Debian, [Window Maker](https://repo.or.cz/wmaker-crm.git/tree) is the only one I know of that has a copy of debian directory upstream.

**Comment by dimpase** [comment] 2020-05-17 20:38
IMHO a copy of debian directory in M2 source would add to confusion (that's extra synchronisation to do following some yet to determine rules, too, and it is going to be not always the same for different versions of Debian...). 

Sagemath used to have such a directory, then its Debian package got broken, people got worried whether it's something that may be fixed by using data  in debian/ directory of Sagemath source, etc. Now debian/ is gone (Debian package is back to life, meanwhile), and this leads to less Debian-specific things asked in general Sagemath forums (and more in a specific "packaging" forum), which is actually better.

**Comment by d-torrance** [comment] 2020-05-31 19:47
Update: mpsolve has been uploaded to Debian.  It will likely sit in the NEW queue for a while before it will be available for Macaulay2 to use.

There are three more packages that still need to get into Debian before it will be ready for Macaulay2:

- topcom, which is ready but waiting for a sponsor to upload it
- two Javascript libraries needed by Visualize that are mostly packaged, but need some more work,.  I'm planning on doing that this week during the workshop.

We also need flint 2.6, which is supposed to be released officially tomorrow.  The Debian maintainer of flint is active and I expect that it will be uploaded while we wait for the others.

**Comment by dimpase** [comment] 2020-05-31 20:19
flint 2.6 will do one more rc before the release, as there are a couple of minor hiccups left.

**Comment by d-torrance** [comment] 2020-06-20 14:09
Update:

* flint 2.6 is now in Debian
* topcom is now in the NEW queue

**Comment by d-torrance** [comment] 2020-06-22 21:20
topcom was accepted quickly!

We're still waiting on the following packages:

- [ ] mpsolve (in NEW queue)
- [ ] node-nouislisder (waiting for a sponsor)
- [ ] bootsidemenu.js (waiting for a sponsor)

If I can't find a sponsor for the two Javascript packages by the time 1.16 is released (and mpsolve is accepted), then I should be able to just include them in Macaulay2 itself for the time being (provided that I include an un-minified version of noUiSlider).

**Comment by DanGrayson** [comment] 2020-06-23 10:42
I didn't realize that the Visualize package has minimized javascript files.  Maybe we should just unminimize them all upstream.


There are 12 of them -- why are you concerned about only 2?  Are the other 10 already to be found in debian?

**Comment by d-torrance** [comment] 2020-06-23 11:55
> There are 12 of them -- why are you concerned about only 2? Are the other 10 already to be found in debian?

Yes, exactly.

**Comment by d-torrance** [comment] 2020-07-09 22:58
The Debian package is in pretty good shape, I think, with the exception of no `roots` function since mpsolve is still sitting in the NEW queue.

My plan is that once the `release-1.16` branch is stable and the new version is announced, I'll ask for sponsorship to get Macaulay2 uploaded to the NEW queue.  This should increase the chances of getting it into Ubuntu 20.10.  (Ubuntu will automatically migrate packages from Debian unstable until August 27.)

Hopefully, by the time it goes through the NEW queue, mpsolve will have also gone through and I can restore `roots` on the second upload.

Also, I've split off the emacs files from `macaulay2-common` into their own binary package, `macaulay2-emacs`, inspired by the [Why install M2-mode without Macaulay2?](https://github.com/Macaulay2/M2-emacs#why-install-m2-mode-without-macaulay2) section of the M2-emacs README.

**Comment by DanGrayson** [comment] 2020-07-10 12:36
Can you point the debian package at a commit number?  Or should we make a tag for you?

I'm building on Debian 10 today, so if that goes okay, you might base it on the commit at that time.  I have further problems on CentOS.

**Comment by DanGrayson** [comment] 2020-07-10 12:38
By the way, I asked Mike whether I could simplify the build of mathicgb and friends, since libtool and automake are causing problems.  I assume you can adapt to that easily.

Is it required, for Debian, that a package such as mathicgb be able to make shareable libraries?   I'd like to not bother with that at all.

**Comment by DanGrayson** [comment] 2020-07-10 12:44
> Update:
> 
> * flint 2.6 is now in Debian

How do I get to use it?

```
debian$ sudo apt-get install libflint-dev
The following packages were automatically installed and are no longer required:
  bliss libbliss2 liblrs0 libpolymake-dev-common libppl14 libterm-readkey-perl libxml-libxslt-perl libxml-writer-perl libxslt1.1
  ninja-build polymake-common sketch
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libflint-2.5.2
The following NEW packages will be installed:
  libflint-2.5.2 libflint-dev
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 1,159 kB/2,075 kB of archives.
After this operation, 12.9 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ftp.us.debian.org/debian stable/main amd64 libflint-dev amd64 2.5.2-19 [1,159 kB]
Fetched 1,159 kB in 1s (1,249 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
Selecting previously unselected package libflint-2.5.2.
(Reading database ... 112695 files and directories currently installed.)
Preparing to unpack .../libflint-2.5.2_2.5.2-19_amd64.deb ...
Unpacking libflint-2.5.2 (2.5.2-19) ...
Selecting previously unselected package libflint-dev.
Preparing to unpack .../libflint-dev_2.5.2-19_amd64.deb ...
Unpacking libflint-dev (2.5.2-19) ...
Setting up libflint-2.5.2 (2.5.2-19) ...
Setting up libflint-dev (2.5.2-19) ...
Processing triggers for libc-bin (2.28-10) ...
```

**Comment by d-torrance** [comment] 2020-07-10 12:46
> Can you point the debian package at a commit number? Or should we make a tag for you?

I wrote a [script](https://salsa.debian.org/science-team/macaulay2/-/blob/watch/m2-get-orig-source.py) that finds the most recent `release-X.Y` branch, builds a tarball from it using `git archive`, and builds a [small webpage](https://science-team.pages.debian.net/macaulay2/) for use by Debian's `uscan` tool, which checks for version bumps and downloads tarballs.  So I'm all set on that end!

**Comment by d-torrance** [comment] 2020-07-10 12:56
> > Update:
> > 
> > * flint 2.6 is now in Debian
>
> How do I get to use it?

It's only in Debian unstable right now.  Apparently it's not building on 32 bit architectures ([#964109](https://bugs.debian.org/964109)), so it hasn't migtrated to testing (Debian 11) yet.  It likely won't become available for Debian 10, since stable releases just get security updates.

**Comment by mahrud** [comment] 2020-07-10 13:03
> By the way, I asked Mike whether I could simplify the build of mathicgb and friends, since libtool and automake are causing problems. I assume you can adapt to that easily.
> 
> Is it required, for Debian, that a package such as mathicgb be able to make shareable libraries? I'd like to not bother with that at all.

@DanGrayson consider using the CMake build for memtailor/mathic/mathicgb. I wrote it this year, so you don't have to do the same. You can do testing as well as creating shared libraries directly as well.

**Comment by d-torrance** [comment] 2020-07-10 13:22
> By the way, I asked Mike whether I could simplify the build of mathicgb and friends, since libtool and automake are causing problems. I assume you can adapt to that easily.
> 
> Is it required, for Debian, that a package such as mathicgb be able to make shareable libraries? I'd like to not bother with that at all.

It's strongly encouraged.  Library packages are generally expected by Debian policy to ship both static and shared libraries, with a few [exceptions](https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#static-libraries).

However, if the Debian package of Macaulay2 were to link against the static libraries instead of shared ones, it would raise a [statically-linked-binary](https://lintian.debian.org/tags/statically-linked-binary.html) Lintian error and likely wouldn't be accepted.

Even if you do make changes to the memtailor/mathic/mathicgb builds, I can just hold off on uploading new versions to Debian until later, since everything works fine building Macaulay2 against the current packages.

**Comment by DanGrayson** [comment] 2020-07-10 13:40
> @DanGrayson consider using the CMake build for memtailor/mathic/mathicgb. I wrote it this year, so you don't have to do the same. You can do testing as well as creating shared libraries directly as well.

Okay, I'll try it!  What would be the syntax for the command?  There is presumably a way to pass such things as compiler flags and libraries to it, and a way to specify whether to build a sharable library.

**Comment by DanGrayson** [comment] 2020-07-10 13:43
> > By the way, I asked Mike whether I could simplify the build of mathicgb and friends, since libtool and automake are causing problems. I assume you can adapt to that easily.
> > Is it required, for Debian, that a package such as mathicgb be able to make shareable libraries? I'd like to not bother with that at all.
> 
> It's strongly encouraged. Library packages are generally expected by Debian policy to ship both static and shared libraries, with a few [exceptions](https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#static-libraries).

Are there other haters of libtool out there who do it a different way?

> 
> However, if the Debian package of Macaulay2 were to link against the static libraries instead of shared ones, it would raise a [statically-linked-binary](https://lintian.debian.org/tags/statically-linked-binary.html) Lintian error and likely wouldn't be accepted.

Wouldn't that just be if the whole of M2-binary were statically linked?  They'd have no way to tell whether a single library is linked into it statically.

> 
> Even if you do make changes to the memtailor/mathic/mathicgb builds, I can just hold off on uploading new versions to Debian until later, since everything works fine building Macaulay2 against the current packages.

No, don't bother, I found another way of working around it: I use `rm -f /usr/local/lib/lib*.dylib`.  (The "gatekeeper" doesn't permit shared libraries inside *.dmg files on the Mac.)

**Comment by d-torrance** [comment] 2020-07-10 13:57
> Are there other haters of libtool out there who do it a different way?

I'm not really sure.  Here's a [wiki page](https://wiki.debian.org/StaticLinking) with a little more about static linking in Debian, but I'm not sure if it answers your question.

> Wouldn't that just be if the whole of M2-binary were statically linked? They'd have no way to tell whether a single library is linked into it statically.

Ah, you're probably right!

**Comment by dimpase** [comment] 2020-07-10 15:14
a reviewer would look at the dependencies and wonder why you link in
statically  a gazillion of libraries.

**Comment by d-torrance** [comment] 2020-07-13 01:48
I think the package is ready!  I've asked for sponsorship to get it uploaded.  So now the process is:

* Wait for a sponsor to review the package.  If it looks good, they may upload it right away, or they might ask me for some changes or make a couple quick fixes themselves.
* Wait while it sits in the NEW queue for the FTP masters to review it.  If it looks good, then it will be uploaded to Debian unstable.  Or they may ask for some changes.  At this stage, it's usually copyright things, e.g., I had to remove the logo from the cohomCalg manual because it had a non-free license.  Some packages go through the NEW queue quickly (e.g., topcom took two days), but some packages are very slow (e.g., mpsolve is still there after about 2 months).
* After it's been in unstable for 10 days, it's eligible for migration to testing.  But there are a couple things that need to happen first:
  - It needs to build on all of Debian's supported architectures.  Currently, flint isn't building on the 32-bit ones, so obviously Macaulay2 won't be able to build on them either until that's fixed.
  - It needs a second, source-only upload.
  - It can't have any "RC" (release critical) bugs.  These are mostly things like build failures and copyright issues.
* Also, once it's in unstable, it will migrate to Ubuntu 20.10 "Groovy Gorilla", assuming this is before their freeze on August 27.  If it's after then (which is probably quite likely), then it won't make it to Ubuntu until 21.04 at the earliest.
* Assuming it makes it to testing (and isn't later removed because of an RC bug) before next year's freeze, then it should be in Debian's next stable release, Debian 11 "bullseye".

**Comment by DanGrayson** [comment] 2020-07-13 09:51
Great!

And then it will migrate automatically into Ubuntu, Raspbian, etc.?

**Comment by dimpase** [comment] 2020-07-13 10:25
Incidentally, we are asked to look at Rasbrian (which is a 32-bit OS for Arm64, whatever this means exactly) support for Sagemath. 
Flint builds there. At least one C++ library, libfplll, needed something ARM-specific, linking with libatomic library.

**Comment by d-torrance** [comment] 2020-07-13 11:21
> And then it will migrate automatically into Ubuntu, Raspbian, etc.?

Yup!  I mentioned the Ubuntu migration schedule above.  I'm not 100% sure about how Raspbian's migration's schedule works (and I can't find any good docs), but it looks like it stays in sync with Debian pretty well.  For example, the newest versions of memtailor, mathic, and mathicgb I packaged a couple weeks ago are already in Raspbian testing.

**Comment by d-torrance** [comment] 2020-10-04 23:05
Exciting update!  The Macaulay2 Debian package has finished going through the sponsorship process and has now been uploaded to the NEW queue:

https://ftp-master.debian.org/new/macaulay2_1.16+git55.94c4b7d+ds-1.html

Now we wait.  Sometimes, this takes days (e.g., topcom took about 2 days to go through the NEW queue) and sometimes this takes months (e.g., mpsolve has been there since the end of May ).

**Comment by DanGrayson** [comment] 2020-10-05 13:58
Great news!

**Comment by mikestillman** [comment] 2020-10-05 14:16
Yes, excellent news indeed!  Thanks Doug!

**Comment by d-torrance** [comment] 2020-10-19 19:55
mpsolve is finally in Debian, so once Macaulay2 finally through the NEW queue, the following upload will have a working `roots` function.

**Comment by d-torrance** [comment] 2020-10-23 22:10
Macaulay2 is now in Debian unstable!

https://tracker.debian.org/news/1185822/accepted-macaulay2-116git5594c4b7dds-1-source-all-amd64-into-unstable-unstable/

**Comment by DanGrayson** [comment] 2020-10-24 00:38
Great!

**Comment by d-torrance** [comment] 2020-10-30 09:32
Good news: Macaulay2 has migrated over to Ubuntu 21.04 (Hirsute Hippo)!

Bad news:  *All* the builds are failing.

* amd64 - an example error in ThreadedGB (maybe #1463?)
* all the other archs: #1554

https://launchpad.net/ubuntu/+source/macaulay2

**Comment by DanGrayson** [comment] 2020-10-30 13:25
I keep having occasional errors in ThreadedGB, too.  The task/thread system has some problems.  Maybe you could patch out the failing example.

**Comment by d-torrance** [comment] 2020-11-25 16:05
At some point, Ubuntu retried the amd64 build and it was successful [1].  So Macaulay2 should be in the release of 21.04 for amd64!

[1] https://launchpad.net/ubuntu/+source/macaulay2/1.16+git55.94c4b7d+ds-1/+build/20212619

**Comment by d-torrance** [comment] 2020-12-08 23:42
Status update:  I'm doing regular builds of Debian packages of the `development` branch that work on amd64, i386, and mips64el.  (I suspect that mipsel works too, but a qemu bug is preventing me from testing it on my machine.)

Since it looks like we've figured out #1554, I'm hopeful that we can get Macaulay2 to build on the other official Debian and Ubuntu architectures.

My tentative plan is to wait until the release of 1.17, package that, and then ask for sponsorship for an upload to Debian.  The process should go much more quickly now that it's already been through the NEW queue.  As long as it migrates to testing by Feb. 12 (https://release.debian.org/bullseye/freeze_policy.html), it should get into the official Bullseye (Debian 11) release.  Similarly, as long as it migrates over to Ubuntu by Feb. 25 (https://discourse.ubuntu.com/t/hirsute-hippo-release-schedule/18539), it should be in the official Hirsute Hippo (Ubuntu 21.04) release (1.16 already is on amd64).

**Comment by DanGrayson** [comment] 2020-12-09 00:56
Great!

**Comment by d-torrance** [comment] 2020-12-17 14:59
For the first time, the Macaulay2 package has built successfully on every architecture on my Ubuntu 21.04 PPA!

https://code.launchpad.net/~profzoom/+recipe/macaulay2-daily-hirsute

![image](https://user-images.githubusercontent.com/1992248/102503567-d713f180-404d-11eb-8586-248e9c375e4e.png)

This isn't all of the official Debian architectures (it's missing armel, i386, mips64el, and mipsel), but it looks like we're in pretty good shape!

**Comment by mikestillman** [comment] 2020-12-17 15:01
Excellent!

**Comment by DanGrayson** [comment] 2020-12-17 15:13
Great!

**Comment by d-torrance** [comment] 2020-12-27 16:45
Update: a package for the 1.16.99 beta release has been uploaded to Debian experimental!  And good news -- it's building on [several more architectures](https://buildd.debian.org/status/package.php?p=macaulay2&suite=experimental) than 1.16 did! In particular, armel, armhf, and i386.

We still have some missing architectures, with various test failures:

* arm64, s390x: #1745
* mips64el: #1557
* mipsel, ppc64: #1746
* ppc64el #1747

It also failed to build on ricsv64 (which is an unofficial architecture) due to a bug in flint, and a slew of other unofficial architectures due to various missing dependencies.

I'll patch out these tests prior to packaging 1.17 once it's released, so hopefully we'll be in better shape then.  It feels like a game of Whack-a-Mole, though.  :)

**Comment by d-torrance** [comment] 2021-01-12 01:00
I've just requested sponsorship for a package based on the `release-1.17.1` tag for Debian unstable.  Fingers crossed that everything builds!

**Comment by DanGrayson** [comment] 2021-01-12 13:32
Okay!

If you're successful, does Macaulay2 end up in Ubuntu 20.10, 20.04, 19.10, etc.  Or just in 21.04?

Once we're in, say to 21.04, do further releases of Macaulay2 find their way to the users of 21.04 promptly?

**Comment by d-torrance** [comment] 2021-01-12 13:51
> If you're successful, does Macaulay2 end up in Ubuntu 20.10, 20.04, 19.10, etc. Or just in 21.04?

Just 21.04.  But I'm planning on releasing PPA packages (using the same `ppa:macaulay2/macaulay2` archive that's used in the Github workflow for various build dependencies) for 18.04, 20.04, and 20.10.  (19.10 has already reached its end of life.)

> Once we're in, say to 21.04, do further releases of Macaulay2 find their way to the users of 21.04 promptly?

Not through the official Ubuntu archives.  Ubuntu 21.04 will be released in April and likely will have 1.17.1 (it already has 1.16, at least for amd64).  It will only get security updates after that.  1.18 will likely end up in 21.10 in October, and so on.

**Comment by d-torrance** [comment] 2021-01-18 16:14
Macaulay2 1.17.1 is now in Debian unstable (and in Ubuntu hirsute-proposed, which eventually migrates into 21.04 "Hirsute Hippo").  The [builds](https://buildd.debian.org/status/logs.php?pkg=macaulay2&ver=1.17.1%2Bds-1) have been going well so far.  As I write this, we're still waiting on two official Debian architectures (mips64el and mipsel), and the only build failures are for non-official architectures.  Most of them have missing dependencies, but two got pretty far into the build:

* powerpc: #1728
* riscv64: #1833

The [Ubuntu builds](https://launchpad.net/ubuntu/+source/macaulay2/1.17.1+ds-1) have also been going pretty well.  The amd64 build, strangely, has been running for 10 hours, but I expect it should be fine, and the only failures have been riscv64 (#1833 again) and s390x (a dependency issue with Emacs).

The continuous integration test for Debian unstable on i386 failed (see #1834), though. It's marked as a regression since it passed for the 1.16.99 package (before `check "Core"` was a thing). But if I'm reading the docs correctly, I don't think this will prevent migration to testing since 1.16.99 isn't in testing.

So fingers crossed, I think it's likely that it will migrate to both Debian testing and Ubuntu hirsute-release in a few days!

**Comment by DanGrayson** [comment] 2021-01-18 20:13
Sounds good!

**Comment by d-torrance** [comment] 2021-01-21 14:40
The 1.17.1 package has migrated from "proposed" into "released" for Ubuntu 21.04, so we're definitely in on the Ubuntu side of things!  Still two more days until the Debian package *might* migrate -- I'm still not clear on whether #1834 will block it or not.  It's fixed (with an ugly hack) in my current draft, but I'll wait until 1.17.2 is released.

I've also published PPA packages based on this for earlier Ubuntu releases (18.04, 20.04, and 20.10).  Would it be worth announcing this on the Google Group and/or adding it as an alternate download location in the Ubuntu section of the webpage?

**Comment by mikestillman** [comment] 2021-01-21 14:48
@d-torrance That is great!  Thanks!!

Yes, we should announce it on the google group, and fix the webpage for that too.  @DanGrayson what do you think?

**Comment by DanGrayson** [comment] 2021-01-21 15:12
That's great!

**Comment by d-torrance** [comment] 2021-01-23 02:06
#1834 indeed blocked the package from migrating to testing.  Is there still a plan to release 1.17.2 soon?  Or I could have 1.17.1 re-uploaded.

**Comment by DanGrayson** [comment] 2021-01-23 13:11
> #1834 indeed blocked the package from migrating to testing. Is there still a plan to release 1.17.2 soon? Or I could have 1.17.1 re-uploaded.

I'm not sure what you mean by re-uploading 1.17.1, but if you want to make a debian release based on something more modern than 1.17.1, I'm happy to bump the version number to 1.17.2 for you, and to make a tag based on that.  Does #1834 have to be fixed before that, though?

**Comment by d-torrance** [comment] 2021-01-23 14:27
> I'm not sure what you mean by re-uploading 1.17.1

I'd keep the same upstream source, but add a ` -2` revision to the Debian version number.  The Debian packaging itself would have a few changes.

> but if you want to make a debian release based on something more modern than 1.17.1, I'm happy to bump the version number to 1.17.2 for you, and to make a tag based on that.

I don't really have a preference, but whatever version I use is likely to be a part of Debian 11 and so will be around for a while (and Ubuntu 21.04, but that's not an LTS release so it's less of an issue).  So if there's a 1.17.2, it would be nice if it's pretty stable.  I think most of the changes since 1.17.1 have been bug fixes and not new features, so that would probably be fine.

> Does #1834 have to be fixed before that, though?

I've fixed it in the Debian package by avoiding `capture` in the `Core` tests on 32-bit architectures in [this patch](https://salsa.debian.org/science-team/macaulay2/-/blob/debian/master/debian/patches/dont-capture-check-core-32-bit.patch).  I did propose the change (for all architectures) upstream in #1835, but withdrew it based on Mahrud's comments.

**Comment by DanGrayson** [comment] 2021-01-23 14:43
I'm under the impression that the current master branch is pretty secure, and could serve as 1.17.2, but I also have no real preference.  Perhaps Mike does.  Mike?  @mikestillman

**Comment by DanGrayson** [comment] 2021-01-23 14:44
PS: I don't see anything wrong with your patch (for 32 bit machines) being incorporated in our code -- it won't affect 99% of our users.

**Comment by d-torrance** [comment] 2021-01-23 14:58
> PS: I don't see anything wrong with your patch (for 32 bit machines) being incorporated in our code -- it won't affect 99% of our users.

Alrighty -- see #1866.

**Comment by DanGrayson** [comment] 2021-01-24 13:08
@d-torrance : Well, maybe we should just let 1.17.1 be the Ubuntu distribution.  That seems simplest for now.

By the way, our release schedule is biannual, same as Ubuntu's, but our dates are a little after theirs: May 15 and Dec 15.   Maybe we should rotate our release schedule to reduce the lag time between our release and the Debian/Ubuntu deadlines.  What would be best?

**Comment by d-torrance** [comment] 2021-01-24 13:19
> @d-torrance : Well, maybe we should just let 1.17.1 be the Ubuntu distribution. That seems simplest for now.

Sounds good.  I'll still try and get it in Debian using the patch from #1866.

> By the way, our release schedule is biannual, same as Ubuntu's, but our dates are a little after theirs: May 15 and Dec 15. Maybe we should rotate our release schedule to reduce the lag time between our release and the Debian/Ubuntu deadlines. What would be best?

I think the current release schedule works pretty well.  Ubuntu freezes migrations from Debian about two months before each release (so February and August for the April and October releases).  So that gives plenty of time to package each new version, find a sponsor, fix build failures, etc.

**Comment by DanGrayson** [comment] 2021-01-24 13:29
Okay, thanks!

**Comment by mikestillman** [comment] 2021-01-24 14:05
> I'm under the impression that the current master branch is pretty secure, and could serve as 1.17.2, but I also have no real preference. Perhaps Mike does. Mike? @mikestillman

I think that is fine.

**Comment by DanGrayson** [comment] 2021-01-25 16:05
@mikestillman -- I now prefer to just stick with 1.17.1, and what you said above is a little ambiguous.  Shall we?

@d-torrance

**Comment by mahrud** [comment] 2021-01-25 16:34
For the record, for the brew build it is preferable to use a versioned tarfile, and that's easiest with a tag. For instance, a week ago a test build from the main branch [passed](https://github.com/Macaulay2/homebrew-tap/actions/runs/502266142), and today it [failed](https://github.com/Macaulay2/homebrew-tap/actions/runs/509111950). There's no cost to a tag, so why not? You don't need to make binary distribution for all of them.

**Comment by DanGrayson** [comment] 2021-01-25 16:51
Yes, certainly, if we bump the version number to 1.7.2, there will be a tag (release-1.7.2) for that.

**Comment by d-torrance** [comment] 2021-01-25 17:53
FYI, 1.17.1 has been re-uploaded to Debian unstable.  In addition to the #1866 patch, it has a few others from the `development` branch that hopefully should help it to build on a few more architectures.

**Comment by DanGrayson** [comment] 2021-01-25 18:13
Thanks!

**Comment by d-torrance** [comment] 2021-01-26 12:40
Good news: The i386 and armhf continuous integration tests are passing!  So they're not blocking the migration to testing any more.

Bad news:  Now the ppc64el build is failing, which *is* blocking migration.  This has happened [twice](https://buildd.debian.org/status/logs.php?pkg=macaulay2&ver=1.17.1%2Bds-2&arch=ppc64el) so far.  I've requested a third build, so fingers crossed.  I'm not sure what's going on.  Both times, it's been killed building relatively small examples.

**Comment by d-torrance** [comment] 2021-01-26 20:51
Third time's the charm!  The ppc64el package finally built, so things are looking very good for migration to testing in a few days.

**Comment by d-torrance** [comment] 2021-01-28 04:51
We did it!  Macaulay2 is in Debian 11 "Bullseye"!

From https://tracker.debian.org/news/1225012/macaulay2-1171ds-2-migrated-to-testing/:

```
FYI: The status of the macaulay2 source package
in Debian's testing distribution has changed.

  Previous version: (not in testing)
  Current version:  1.17.1+ds-2
```

Note that "testing" will become "stable" at some point later this spring when Bullseye is officially released.  (Unlike Ubuntu, Debian doesn't have a set release date.  It's released when it's ready.)

**Comment by d-torrance** [comment] 2021-01-28 04:52
I suppose we can close this issue now.

**Comment by DanGrayson** [comment] 2021-01-28 18:42
> We did it! Macaulay2 is in Debian 11 "Bullseye"!
> 

Great!!

**Closed** 2021-01-28 18:43 UTC
