### ISSUE TITLE
compatiblity with ntl-8.*

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#214] opened 2015-03-26 10:10 UTC
Hi, 
ntl is having lot's of new versions with interface changes. It seems Macaulay2 is not compatible with ntl-8.* because there are some conversion restrictions now:

    NTLconvert.cc: In function ‘CanonicalForm convertZZ2CF(const NTL::ZZ&)’:
    NTLconvert.cc:505:33: error: invalid cast from type ‘const NTL::WrappedPtr<void, NTL::ZZ::Deleter>’ to type ‘long int*’
     long sizeofrep= ((long *) a.rep) [1];
                                 ^
    NTLconvert.cc:523:79: error: invalid cast from type ‘const NTL::WrappedPtr<void, NTL::ZZ::Deleter>’ to type ‘long int*’
     int cc= mpn_get_str (cf_stringtemp, 16, (mp_limb_t *) (((long *) (a.rep)) + 2), sizeofrep);
                                                                               ^
    Makefile:1162: recipe for target 'NTLconvert.lo' failed

**Comment by tom111** [comment] 2015-03-26 10:52
The friends from Kaiserslautern have already made a patch here:
https://github.com/Singular/Sources/commit/de688442dfe449992dc14a000bca0691ecc7e106

**Comment by DanGrayson** [comment] 2015-03-27 17:47
Then the solution is to make factory a submodule of Macaulay2, so we can pull in any version we want.  I'll do that.

**Comment by DanGrayson** [comment] 2015-03-27 17:48
We can update the ntl version we compile when it's not found.  I assume, though, that ntl was found on your system.

**Comment by tom111** [comment] 2015-03-28 09:34
Yes, I'd prefer to have only copy of ntl on my system (installed by the package manager) and have M2 link against that.  The simple patch makes factory compatible with all available ntl versions, so it's the best solution.

**Comment by DanGrayson** [comment] 2015-04-01 12:38
Okay, I've reproduced the error with ntl 9.

**Comment by DanGrayson** [comment] 2015-04-13 17:25
I got a new official version of Singular-Factory via Hans Schoenemann, and using that has fixed the problem, see https://github.com/Macaulay2/M2/pull/221

**Comment by DanGrayson** [comment] 2015-04-13 21:27
... except we have code in the e directory that is incompatible with the latest ntl, so I've backed off on the change ...

**Comment by DanGrayson** [comment] 2015-04-15 00:47
... and I'm assigning the issue to Mike ...

**Comment by mikestillman** [comment] 2015-04-15 00:50
So you didn’t roll this back?  I’ll work on fixing it.

**Comment by DanGrayson** [comment] 2015-04-15 01:10
Yes, I rolled it back.  But it needs to be fixed, anyway, because ntl 8
exists in the wild, and we'll try to use it.

**Comment by DanGrayson** [comment] 2015-04-15 01:11
Could you determine which version of ntl introduced the new pointer
wrapping?  Then I can
have our configure script insist that ntl is at least that new.

**Comment by mikestillman** [comment] 2015-04-15 02:32
> Could you determine which version of ntl introduced the new pointer
> wrapping?  Then I can have our configure script insist that ntl is at least that new.

Dan, I don’t understand your comment.  NTL isn’t working on newer versions, right?  Or do you mean, after I fix it?

Why is there a change in the configure (+ refers to old NTL, - to new one)?  NTL_STD_CXX=on isn’t needed for new ntl.?

Commit: 9bfd72707e65e2d04cab8ba100a4503d7fe378ce

-CONFIGUREOPTIONS =				\
-	WIZARD=off				\
-	PREFIX=@pre_libm2dir@			\
-	LIBDIR=@pre_librariesdir@		\
-	INCLUDEDIR=@pre_libm2dir@/include	\
-	DOCDIR=@pre_libm2dir@/share/doc		\
-	NTL_GMP_LIP=on NTL_NO_INIT_TRANS=on	\
-	RANLIB="@RANLIB@"			\
-	CXX="@CXX@"				\
-	CXXFLAGS="$(CXXFLAGS) $(DEB_CXXFLAGS)"	\
-	CPPFLAGS="$(CPPFLAGS) $(DEB_CPPFLAGS)"	\
-	LDFLAGS="$(LDFLAGS) $(DEB_LDFLAGS)"
+CONFIGUREOPTIONS =						\
+	WIZARD=off						\
+	PREFIX=@pre_libm2dir@					\
+	LIBDIR=@pre_librariesdir@				\
+	INCLUDEDIR=@pre_libm2dir@/include			\
+	DOCDIR=@pre_libm2dir@/share/doc				\
+	NTL_GMP_LIP=on NTL_STD_CXX=on NTL_NO_INIT_TRANS=on	\
+	RANLIB="@RANLIB@"					\
+	CXX="@CXX@"						\
+	CXXFLAGS="$(CXXFLAGS) $(DEB_CXXFLAGS)"			\
+	CPPFLAGS="$(CPPFLAGS) $(DEB_CPPFLAGS)"			\
+	LDFLAGS="$(LDFLAGS) $(DEB_LDFLAGS)"			\

**Comment by DanGrayson** [comment] 2015-04-15 16:28
Somehow that option NTL_STD_CXX wasn't recognized as an option any more.

The problem for us, when trying to compile with newer NTL, is that your code in ntl-internal.cpp no longer compiles.  So you can start by undoing the rollback in commit 9bfd727 and try to compile.  The data type for an NTL item has changed.

I don't know what you mean by "NTL isn’t working on newer versions".

My comment about detecting the version number means that after you fix your code to work with newer NTL versions, it will no longer work with older NTL versions, which we should try to avoid using if we encounter them.

**Comment by tom111** [comment] 2015-04-15 18:20
The reason for the removed CXX symbols is that in newer versions of ntl C++ support is mandatory. 


--
http://www.thomas-kahle.de

**Comment by mikestillman** [comment] 2015-05-07 02:03
Fixed in commit 2c37e2d2f157faf3de60aad202a78f781edb9d53.

The only place that NTL is currently used is in computing LLL bases.  The translation to/from NTL integers used internal information.  This code has been rewritten.

**Closed by mikestillman** 2015-05-07 02:03 UTC
