### ISSUE TITLE
make tests needing internet skippable

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/M2#887] opened 2018-11-12 19:14 UTC
Currently, `make check` produces errors on tests needing internet access, if the latter fails during the run (something not unusual with wireless internet).
E.g.
```
i1 : --/mnt/opt/M2/M2/M2/Macaulay2/packages/ReflexivePolytopesDB.m2:790: location of test code
     
       debug needsPackage "ReflexivePolytopesDB"

i2 :   -- testing retrieval and parsing for the 4D polytope case, using 
       str = getKreuzerSkarke(3, Limit=>10);
http://quark.itp.tuwien.ac.at/cgi-bin/cy/cydata.cgi?h11=3&L=10
stdio:5:9:(3): error: can't open socket : Temporary failure in name resolution
```

This is certainly not what one would like here.

**Comment by mikestillman** [comment] 2018-11-12 19:48
What is the best way to test it?  It also sometimes fails when the web site is down.  But I would like the package to be on the test path.  Actually, it also needs the internet when it builds examples, during 'make'.

**Comment by dimpase** [comment] 2018-11-12 20:13
Can you run tests with few examples stored locally for this package, if fetching data fails?

**Comment by mikestillman** [comment] 2018-11-12 20:16
I can, but then we never see that fetching fails.  But I think that will need to be done.  I am assigning myself to this.

**Comment by mikestillman** [comment] 2018-11-12 20:20
Alternatively, we could do like we do when we interface to a program that might not be on the users machine (e.g. bergman). (Only build doc nodes if access to the database is alive).  I'll see if that works too.  The trouble is, there are 2 ways for it to fail: (1) the user is basically offline, and (2) the user is online, but the website is down.  This latter one is harder to test, as it only happens every now and then.  @DanGrayson , @dimpase do you know how curl and/or wget fail under these two scenarios?

**Comment by DanGrayson** [comment] 2018-11-13 07:31
I doubt wget and curl distinguish between those cases, but you could test a few other sites, such as www.math.uiuc.edu, and if they are up, go ahead with the test.

**Comment by dimpase** [comment] 2018-11-13 11:49
to me, cases (1) and  (2) are more or less the same - user and the database live in different connected components of the net :-) (it could be a firewall problem, a proxy problem, etc)

you can analyse the exit code of wget/curl. wget’s exit code will be 4 or bigger, and for curl 5 or bigger ( curl has a huge number of return codes though, so perhaps it is not totally right for curl).

**Comment by dimpase** [comment] 2018-11-13 17:35
One can have an option, something like `--enable-database-download=yes/no`, affecting how `make check` operates. So that after running configure with `--enable-database-download=no` tests needing internet connection are just skipped.

An alternative would be to tag (in source code) tests with requirements for them to run, but I guess M2 does not have this (this is how such dependencies are handled in Sage - e.g. tests needing M2 are tagged `# optional - macaulay2`, tests needing internet  are tagged `#  optional - internet`. This is due to tests actually being in multi-line comments in the source...)

**Comment by DanGrayson** [comment] 2018-11-13 17:47
Too confusing for the builder.  It's probably better to just let `--enable-download` do double duty.

**Comment by DanGrayson** [comment] 2018-11-14 08:56
I don't see that as a real problem.  When the internet is working, use --enable-download=yes and you can get all the tarballs.  If the database website is down, then switch to --enable-download=no without deleting the tarballs and the database access will be skipped (under my proposal, where we would use the value of the option to set the value of the option RerunExamples to installPackage (somehow?)).

Maybe you'll say that the database website is down so often that we should give builders a way of just doing everything in one go, by always using --enable-download=yes  --enable-database-access=no.  But if the database website is really so unreliable, then we want to stop using it, anyway.

There's no good way to have the example code "try" the web, since the output from the example run is used to make the documentation.

**Comment by mikestillman** [comment] 2019-05-23 15:00
Duplicate of Issue #664, at least the ReflexivePolytopesDB package no longer needs web access during installation.

**Closed by mikestillman** 2019-05-23 15:00 UTC
