### ISSUE TITLE
Port enhacement request

### ISSUE THREAD

**Issue by sommars** [Macaulay2/M2#681] opened 2017-08-08 21:33 UTC
Per our conversation in Atlanta (@coneill-math, @mikestillman), Chris and I have made a minimal example of the porting issue.

M2 Session 1:
```
x = openInOut "$:27437"
isOpen x --This evaluates to true, but will only run after the second session has been launched.
```

M2 Session 2:
```
x = openInOut "$localhost:27437"
isOpen x --This evaluates to true
```

Close M2 Session 1.
In M2 Session 2, run `isOpen x`. This returns true, but the other side of the connection has been dropped. We want a way for M2 Session 2 to know that the other side of the connection has been dropped.

**Comment by DanGrayson** [comment] 2017-08-08 23:24
I think if one side closes the connection, then on the other side `isReady x` and `atEndOfFile x` will become true.  Also see `wait`.

**Comment by coneill-math** [comment] 2017-08-10 16:50
The problem with using `isReady` is that it must be used together with `sleep` which can only wait an integer number of seconds.  This results in an unreasonable response time, especially when several calls happen in quick succession (since each must have at least one full second in between).  

As it turns out, `wait` has the same issue as `read` in that it will not detect if the remote connection is closed.

**Comment by DanGrayson** [comment] 2017-08-10 17:26
I just did an experiment with `wait` under Mac OS X and it works great.

**Comment by coneill-math** [comment] 2017-08-14 14:02
After trying `wait` on our end, I can confirm it works as expected.  The following appears to do exactly what we need.  

```
m2rintinout = openInOut concatenate("$:", 27436);
while (not isReady m2rintinout and not atEndOfFile m2rintinout) do (
  wait m2rintinout;
);
if (atEndOfFile m2rintinout) then break;
m2rintinline = read m2rintinout;
if (atEndOfFile m2rintinout or m2rintinline == "") then break;
```

Thank you for your help!

**Comment by DanGrayson** [comment] 2017-08-14 15:34
Great!

Closing.

**Closed by DanGrayson** 2017-08-14 15:34 UTC

**Comment by DanGrayson** [comment] 2017-08-14 15:35
Try omitting `m2rintinline == ""`.  It would look better.
