### ISSUE TITLE
dimension of the empty set

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#546] opened 2016-12-20 10:20 UTC
if I=ideal 1_R for some polynomial ring then 
dim I = -1
but
dim (R/I) = -infinity
I don't have a strong opinion which answer is the correct one, but one way or another one should always have dim I := dim (R/I)...
changing might break some packages (and programs, obviously), but probably nothing that can't be easily fixed.

**Comment by eisenbud** [comment] 2016-12-20 14:13
I would vote for -1, keeping the relation between affine and projective dimension constant.

This begs the question: what is the dimension of the unit ideal! — maybe that’s -\infty in both cases.

David
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics,University of California, Berkeley
www.msri.org/~de

**Comment by DanGrayson** [comment] 2016-12-20 14:26
Doesn't -∞ also preserve  the relation between affine and projective dimension ?

**Comment by eisenbud** [comment] 2016-12-20 14:30
(t)\subset k[t] is a 0-dimensional ideal, Spec k[t]/(t) a 0-dimensional scheme; and I’d expect the dimension of the projective variety to be 1 less.

this works with (1)\subset k[t] having dimension -\infty, too.

D
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics,University of California, Berkeley
www.msri.org/~de

**Comment by DanGrayson** [comment] 2016-12-20 14:46
Oh.  Then since we'd also like R and Spec R to have the same dimension, we need the zero ring to have dimension -1, not -∞.

**Comment by eisenbud** [comment] 2016-12-20 14:48
I don’t see that…

D
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics,University of California, Berkeley
www.msri.org/~de

**Comment by DanGrayson** [comment] 2016-12-20 14:50
We want Proj (k[t]/(t)) to be -1.  But it's the empty scheme, so is isomorphic to Spec(0).  So that has to be dimension -1, too.  So dim 0 has to be -1, too.

**Comment by mikestillman** [comment] 2016-12-20 15:36
This makes sense to me for a reason why the dimension of the empty scheme (and therefore of the unit ideal) should be -1.  It is probably easier to work with too.

— mike

**Comment by pzinn** [comment] 2016-12-21 13:06
I'm happy to take care of this change... once my current pull request, as well as the one coming next, are accepted :-P

**Comment by DanGrayson** [comment] 2016-12-21 14:45
Okay, I'll start plowing through the pull requests...

**Comment by DanGrayson** [comment] 2016-12-28 01:54
Your pull request was merged.

Another issue to think about is whether "codim I" should ever be infinity, in light of this code:
```

i24 : code (dim, QuotientRing)

o24 = -- code for method: dim(QuotientRing)
      ../../src/M2/M2-Macaulay2/M2/Macaulay2/m2/quotring.m2:271:25-278:30: --source code:
      dim QuotientRing := (R) -> (
           if isField R then 0
           else if R.?SkewCommutative then notImplemented()
           else (
                I := flattenRing(R, Result => Ideal);
                dim ring I - codim I
                )
           )
```

**Comment by pzinn** [comment] 2017-01-05 00:04
Indeed, the problem is that codim I returns infinity (not an absurd convention, which probably shouldn't be changed).
Incidentally, before I look further into this, can someone remind me what the following definition does:
(which is called by codim Ideal)
```
codim Module := codimopts >> opts -> (cacheValue (symbol codim => opts)) (M -> runHooks(Module, symbol codim, (opts,M)))
```

**Comment by DanGrayson** [comment] 2017-01-05 01:08
`cacheValue` saves the answer for next time.

`runHooks` runs all the "hook" routines, previously installed, until one claims to give the answer

**Comment by pzinn** [comment] 2017-01-06 04:46
ah right, silly me. the hook is defined right below in the same file monideal.m2.
back to work...

**Comment by pzinn** [comment] 2017-01-11 03:30
Of course, I opened a can of worms...
The obvious solution would be to set dim QuotientRing := (R) -> (various trivial cases) else dim ideal R
but then, just to be sure, I tested the behavior of dim Ideal... here's a particularly interesting one:
(note that this is *before* making any change to dim QuotientRing!)
```
i1 : R=QQ[x,y]

o1 = R

o1 : PolynomialRing

i2 : R2=R/ideal(x,y)

o2 = R2

o2 : QuotientRing

i3 : R3=R2[t]

o3 = R3

o3 : PolynomialRing

i4 : R4=R3/ideal t

o4 = R4

o4 : QuotientRing

i5 : dim R4

o5 = 0

i6 : dim ideal R4

o6 = -2
```

**Comment by pzinn** [comment] 2017-01-11 04:18
To make my point clearer: the current code for dim QuotientRing may be redundant, but one thing it treats properly is such iterated rings. dim Ideal, however, doesn't. note that codim is fine.
I'm not immediately offering a solution, because this is somewhat subtle.
The problem lies in the code
```
dim Module := M -> (
     c := codim M;
     if c === infinity then -1 else dim ring M - c
     )
```
codim M is computed by effectively flattening the ring; but dim ring M isn't (i.e., if along the way in forming ring M there were some quotients, they will be subtracted from dim ring M, resulting here in dim R3 = 1, which is correct but not what is needed here)

**Comment by DanGrayson** [comment] 2017-01-11 14:26
That's a great bug for you to debug!

The problem is in the code for "codim Module", since it returns 3, which is larger than the dimension of the ring:
```
i7 : codim M

o7 = 3

i8 : dim ring M

o8 = 1
```

**Comment by pzinn** [comment] 2017-01-23 04:41
OK I'll work on it as soon as I find the time.

**Comment by pzinn** [comment] 2017-06-28 02:59
just a quick update, since I've been stuck on this for a long time. I've traced back the problem to codim monomialIdeal, which suffers from the same problem; with the same example,

`i56 : monomialIdeal ideal R4

o56 = monomialIdeal (t, 0, 0)

o56 : MonomialIdeal of R3

i57 : codim oo

o57 = 3`

Note how monomialIdeal is clearly confused by the quotient by ideal(x,y), since it thinks o56 has 3 generators, even though two are zero... and incorrectly concludes that the codimension is 3.
I shudder at the thought of rewriting some of these monomialIdeal routines, and how it would affect everything else. More realistically, I think monomialIdeal should refuse to deal with such iterated rings. But this doesn't help with resolving the current issue.

**Comment by pzinn** [comment] 2017-06-28 04:34
... to continue: to a large extent, the current code for codim Module relies on a loophole: that newMonomialIdeal(...) doesn't check that the ambient ring isn't something weird (as opposed to say MonomialIdeal Matrix, which at least checks that it isn't a quotient ring). It seems some packages use this feature/bug (for ex Cremona.m2 uses codim of modules in quotient rings), so I'm not touching this.

**Closed** 2017-08-05 13:24 UTC
