### ISSUE TITLE
Ideal membership fails without first computing gb (when multidegrees have negative entries)

### ISSUE THREAD

**Issue by sacsar** [Macaulay2/M2#88] opened 2014-01-22 21:42 UTC
In the following, `f` is a member of `I`, but `f % I` is not 0 unless one first explciitly computes a Gröbner basis for `I`. If one changes the multidegrees to only have positive entries, `f % I` seems to be 0 on the first attempt.
```
i1 : A = transpose matrix {{1,0,0},{0,-1,0},{0,0,-1},{1,1,0},{1,0,1},{1,1,1}};
o1 : Matrix ZZ^3  <--- ZZ^6
i2 : S = QQ[U1,Um2,Um3,U12,U13,U123,Degrees=>entries transpose A];
i3 : f = U12*U13-U1*U123;
i4 : I = ideal(Um2*U12-U1,Um2*U123-U13,Um3*U13-U1,Um3*U123-U12,U12*U13-U1*U123);
o4 : Ideal of S
i5 : f % I
o5 = - U1*U123 + Um2*Um3*U123^2
o5 : S
i6 : f // gens I
o6 = {1, 0, 0} | U123 |
        {1, 0, 1} | -U12 |
        {1, 0, 0} | 0    |
        {1, 1, 0} | 0    |
        {2, 1, 1} | 0    |
o6 : Matrix S^5  <--- S^1
i7 : (gens I) * oo - f
o7 = 0
o7 : Matrix S^1  <--- S^1
i8 : gb I;
i9 : f % I
o9 = 0
o9 : S
```

**Comment by mikestillman** [comment] 2015-05-12 02:01
Dan, the problem with this issue still persists.  The problem is that the engine code is taking the value of the DegreeLimit option to be a list of integers of length 0 or 1 (length 0: no limit), (length 1: heft value to stop computation after).

However, the code you mention above is placing the actual degree in the value.

There are two ways to fix this:
1. change the code above to send the heft value (as a one element list).
2. change the engine code to compute the heft value of this degree.

I suppose that we should choose option (2).  Do you see any ramifications either way?

**Comment by DanGrayson** [comment] 2015-05-12 12:45
Oh, that's why!  Oy.  I suppose by "heft value" you mean the dot product of ```heft S``` with ```degree f```.  Option (1) seems quickest, but the choice doesn't seem to matter.

**Comment by mikestillman** [comment] 2015-05-12 12:48
We would need to check everyplace that DegreeLimit is used in the distribution.  I’ll bet there aren’t that many cases.

**Comment by DanGrayson** [comment] 2015-05-12 13:36
We could start by having the interface routine check that the length of the
list is at most 1!

**Comment by DanGrayson** [comment] 2015-05-12 13:57
I'd be happy to take care of it if you re-assign it to me.

**Comment by mikestillman** [comment] 2015-05-12 13:59
OK, I think I've re-assigned it.  Thanks!

**Comment by DanGrayson** [comment] 2015-05-12 14:20
Same deal for ```HardDegreeLimit```?

**Comment by DanGrayson** [comment] 2015-05-12 15:33
Fixed in commit 2a5fde01d6894dd63ed445a6b4faa1eead5211f3.  I'll close after auditing HardDegreeLimit as well.

**Comment by mikestillman** [comment] 2015-05-12 16:14
Yes.

**Comment by DanGrayson** [comment] 2015-05-30 22:07
I added a test in commit 2d04b2b9e02c0b3bce266426a98bc8c6ec15d62b

**Comment by DanGrayson** [comment] 2015-05-30 22:21
I changed one thing about ````HardDegreeLimit``` in commit 21c0c8bfb0d236742889d4febb0ae1db802c1a79.

**Closed by DanGrayson** 2015-05-30 22:21 UTC
