### ISSUE TITLE
Compiling with gcc-5.2 leads to segmentation faults (on Mac OS)

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#334] opened 2015-08-28 14:23 UTC
I just tried to build the latest master with gcc-5 from homebrew on MacOS. Compilation finishes, but the binary seems to be defective.  When building the Macaulay2Doc package, the following fail (I can't spot an obvious pattern...):

```
ls *.errors
___G__Rev__Lex.errors                                              _dual_lp__Monomial__Ideal_rp.errors
___H__H^__Z__Z_sp__Chain__Complex.errors                           _frac.errors
___Lex.errors                                                      _groebner__Basis.errors
___Monomial__Ideal.errors                                          _is__Square__Free.errors
_associated__Primes_lp..._cm_sp__Strategy_sp_eq_gt_sp..._rp.errors _minimal__Primes.errors
_dim_lp__Ideal_rp.errors                                           _standard__Pairs.errors
```

All of these contain segmentation faults like here:

```
cat ___Lex.errors
-- -*- M2-comint -*- {* hash: -1969480400 *}
[...]
i5 : C = QQ[a..d,MonomialOrder=>Lex,MonomialSize=>8];
i6 : try a^(2^15-1) else "failed"
-- SIGSEGV
-- stack trace, pid 76803:
level 0 -- return addr: 0x0x10a0d425f -- frame: 0x0x1106e2e00
level 1 -- return addr: 0x0x10b1f2a3c -- frame: 0x0x1106e2e20
level 2 -- return addr: 0x0x10a15d8da -- frame: 0x0x1106e33a0
-- end stack trace
```

This was with 

```
gcc-5 --version
gcc-5 (Homebrew gcc5 5.2.0) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Then I tried all the same with 

```
gcc-4.9 --version
gcc-4.9 (Homebrew gcc49 4.9.3) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

and everything is fine.

**Comment by DanGrayson** [comment] 2015-08-28 14:37
I've had the same trouble with gcc 5 on Mac OS X, so am sticking to 4.9 for now.  It 
would be good to figure out what's wrong.

**Comment by tom111** [comment] 2015-09-20 17:22
Crosslinking: https://groups.google.com/forum/#!topic/macaulay2/NQCziO8wHxc

**Comment by thelongdiv** [comment] 2015-09-20 17:31
It very likely is.  I think, for at minimum arch and other OS running flint 2.5+, it should be included in the INSTALL file that --enable-build-libraries=flint should be included.

**Comment by DanGrayson** [comment] 2016-05-09 18:18
Gcc 6 is available now, so we should try that.

**Comment by DanGrayson** [comment] 2016-05-09 18:58
To try or to debug the development version, one can use the source code of gcc here: https://gcc.gnu.org/wiki/GitMirror

**Comment by tom111** [comment] 2016-05-10 07:44
Some experiences from compiling today's head 5ea9f5e with gcc-6 on MacOS:
I used the homebrew version of gcc-6 with following configure:

    CC=gcc-6 CXX=g++-6 CPP=cpp-6 LD=gcc-6 ../../configure --enable-download

In particular, I use flint-2.5.2 built on the local machine with gcc-6. I first ran into [issue 430](https://github.com/Macaulay2/M2/issues/430) and after fixing it (by passing zero in the macro) the binary was defunctional as follows:

```
touch .gdbinit.tom
cp .gdbinit.tom .gdbinit
echo 'echo -- loading .gdb-files\n' >.gdb-files
echo 'set environment LD_LIBRARY_PATH /Users/tom/temp/M2/M2/BUILD/tom/usr-host/lib:' >>.gdb-files
echo 'file /Users/tom/temp/M2/M2/BUILD/tom/usr-dist/x86_64-Darwin-MacOS-10.11.4/bin/M2-binary' >>.gdb-files
echo 'echo -- loading .gdb-run-it\n' >.gdb-run-it
echo 'echo \n' >>.gdb-run-it
echo 'run -q --no-loaddata --no-readline --no-personality' >>.gdb-run-it
/Users/tom/temp/M2/M2/BUILD/tom/usr-dist/x86_64-Darwin-MacOS-10.11.4/bin/M2 -q --silent --stop -e errorDepth=0 --no-tvalues ../../../../Macaulay2/m2/tvalues-make.m2 -e 'make "../../../../Macaulay2/m2/../d/"; exit 0'
M2-binary(78694,0x70000118d000) malloc: *** error for object 0x106b0afe0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
make[2]: *** [tvalues.m2] Abort trap: 6
make[2]: *** Deleting file `tvalues.m2'
make[2]: Leaving directory `/Users/tom/temp/M2/M2/BUILD/tom/Macaulay2/m2'
make[1]: *** [all-in-m2] Error 2
make[1]: Leaving directory `/Users/tom/temp/M2/M2/BUILD/tom/Macaulay2'
make: *** [all-in-Macaulay2] Error 2
make: Leaving directory `/Users/tom/temp/M2/M2/BUILD/tom'
```

**Comment by DanGrayson** [comment] 2016-05-10 12:37
I started a compile with gcc 6 yesterday, too, so maybe I can reproduce what you found and debug it.

**Comment by DanGrayson** [comment] 2016-08-20 15:32
Compiling against gcc 6 would be helpful, since Arch Linux no longer even offers gcc 4.  See #513.

**Comment by dimpase** [comment] 2016-08-21 19:34
It is possible to build working M2 on Fedora 23 Linux with gcc 5.3.1. On Arch one most probably should downgrade gcc to this version (or a newer,  gcc 5.4 - I don't know what they carry).

At least this is the case of building Sagemath on Arch - one has to downgrade gcc to gcc 5.

**Comment by DanGrayson** [comment] 2016-08-21 21:18
We've never succeeded building M2 with gcc 5.

**Comment by dimpase** [comment] 2016-08-21 21:26
@DanGrayson : well, try gcc 5.3.1 on a sane (:-))  OS. On Fedora 23 it certainly builds and passes most tests in `make check` (at the end of the output there are few messages about deferred tests, but it's probably good enough still; do you need more info on this?)

**Comment by DanGrayson** [comment] 2016-08-21 21:39
Did it say, near the end, that all the tests passed?

**Comment by DanGrayson** [comment] 2016-08-21 21:40
Is Mac OS X sane?

**Comment by dimpase** [comment] 2016-08-21 21:47
At the end there was something not error-free happening with "quarantined" tests. Before that I did not see errors; I can re-run tests; would a standard redirecting stdout/stderror to a file work?

**Comment by dimpase** [comment] 2016-08-21 21:51
Sagemath does not consider OSX too sane, e.g. because there is no native (and free) Fortran compiler available. The install of Sagemath on OSX starts by building gcc-4.9.3 from source, and proceeds to use it. There did not seem to be much demand for gcc 5 on OSX, so noone bothered to upgrade yet.

**Comment by DanGrayson** [comment] 2016-08-21 22:22
Did the message "+++ all Macaulay2 tests succeeded +++" appear?

**Comment by dimpase** [comment] 2016-08-21 22:44
Upon re-running, I got an error in MinimalPrimes (I guess that was the only one). Here is the log:  http://users.ox.ac.uk/~coml0531/makecheck.log

**Comment by DanGrayson** [comment] 2016-08-21 22:53
Well, just one error -- that's better than I recall getting, but still not good enough.

**Comment by dimpase** [comment] 2016-08-22 12:13
@DanGrayson : I did re-run the failing example few times manually, and it did pass.
the example in question is the second minprimes call (C2) in the following:
```
  needsPackage "MinimalPrimes"
  R = QQ[x,r,v,u,b, MonomialOrder=>{Lex=>5}]
  I = ideal(b^3-7*b^2+14*b-7,r^2-u*r+(-2*b^2+9*b-5)*u^2+b^2-4*b,x^2+(b-2)*x*r+r^2+b^2-4*b)
  time C1 = minprimes(I, Verbosity=>2)
  assert(#oo == 2)

  R = QQ[b][u][x,r,v, MonomialOrder=>{Lex=>3}]
  I = ideal(b^3-7*b^2+14*b-7,r^2-u*r+(-2*b^2+9*b-5)*u^2+b^2-4*b,x^2+(b-2)*x*r+r^2+b^2-4*b)
  time C2 = minprimes(I, Verbosity=>2)
  assert(#oo == 2)
```

Either running this whole script, or only computation of C2, all works. So this is hard to explain, why `make check` did not work on it.

**Comment by DanGrayson** [comment] 2016-08-22 12:25
Well, a bug in a C program can be highly environment dependent.  What does
it say in the log file
/tmp/M2-20738-0/128.tmp ?


On Mon, Aug 22, 2016 at 8:13 AM, Dima Pasechnik <notifications@github.com>
wrote:
>
> @DanGrayson : I did re-run the failing example few times manually, and it
did pass.
> the example in question is the second minprimes call (C2) in the
following:
>
>   needsPackage "MinimalPrimes"
>   R = QQ[x,r,v,u,b, MonomialOrder=>{Lex=>5}]
>   I =
ideal(b^3-7*b^2+14*b-7,r^2-u*r+(-2*b^2+9*b-5)*u^2+b^2-4*b,x^2+(b-2)*x*r+r^2+b^2-4*b)
>   time C1 = minprimes(I, Verbosity=>2)
>   assert(#oo == 2)
>
>   R = QQ[b][u][x,r,v, MonomialOrder=>{Lex=>3}]
>   I =
ideal(b^3-7*b^2+14*b-7,r^2-u*r+(-2*b^2+9*b-5)*u^2+b^2-4*b,x^2+(b-2)*x*r+r^2+b^2-4*b)
>   time C2 = minprimes(I, Verbosity=>2)
>   assert(#oo == 2)
>
> Either running this whole script, or only computation of C2, all works.
So this is hard to explain, why make check did not work on it.

**Comment by dimpase** [comment] 2016-08-22 12:28
here is the relevant part:
```
...
i8 :   time C2 = minprimes(I, Verbosity=>2)
  Strategy: Linear            (time .000112502)  #primes = 0 #prunedViaCodim = 0
  Strategy: DecomposeMonomials(time .000029894)  #primes = 0 #prunedViaCodim = 0
  Strategy: Factorization     (time .000843835)  #primes = 0 #prunedViaCodim = 0
  Strategy: Birational        (time .00219857)  #primes = 0 #prunedViaCodim = 0
  Strategy: IndependentSet    (time .00922409)  #primes = 0 #prunedViaCodim = 0
  Strategy: SplitTower        -- SIGSEGV
-- stack trace, pid 22406:
level 0 -- return addr: 0x0x45f95f -- frame: 0x0x7fffefa30d60
level 1 -- return addr: 0x0x27177a0 -- frame: 0x0x27177e0
level 2 -- return addr: 0x0x545ca40 -- frame: 0x0x27177c0
-- end stack trace
```

**Comment by DanGrayson** [comment] 2016-08-22 12:37
We've seen that before and never managed to find the bug, see https://github.com/Macaulay2/M2/issues/190#issuecomment-241399080 , thanks.

Since it's a crash and not an incorrect answer, and it doesn't always crash, it might not be so bad to release it for use by others, but it would be nice to locate the bug.

**Comment by dimpase** [comment] 2016-08-22 14:27
I did one more `make check` run, and got an error in "deferred" tests.
 http://users.ox.ac.uk/~coml0531/makecheck1.log

**Comment by DanGrayson** [comment] 2016-08-22 14:58
I just built it successfully under ArchLinux with gcc 5.4.0, and have posted the resulting binaries on the web site.  All the tests passed.

**Comment by DanGrayson** [comment] 2016-08-22 15:00
I fixed the problem with glpsol not being stripped a few days ago.  Perhaps you are not up to date on the release-1.9.2 branch.

**Comment by dimpase** [comment] 2016-08-22 15:12
I'm on `master` branch. Do you mean to say that release-1.9.2 is ahead of it in part?

**Comment by DanGrayson** [comment] 2016-08-22 15:38
Oops, I forgot to check it in.  Now the fix is included on both branches.

**Comment by DanGrayson** [comment] 2018-12-28 22:53
This issue seems stale, closing.

**Closed by DanGrayson** 2018-12-28 22:53 UTC
