### ISSUE TITLE
documentation on personal web pages

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1001] opened 2019-09-16 11:32 UTC
The documentation at https://www.math.uni-sb.de/ag/schreyer/home/M2/doc/Macaulay2/MatFacCurvesP4/html/ is missing the appropriate style file.  Figure out how users can install documentation with the style file.

**Comment by mahrud** [comment] 2024-11-19 00:35
Closing as duplicate of  #625.

**Closed by mahrud** 2024-11-19 00:35 UTC
Labels: enhancement
