### ISSUE TITLE
configuration files

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1009] opened 2019-09-17 13:04 UTC
The configuration file for DiffAlg sets the global variable i in the User dictionary.  This sort of thing might be too intrusive for users.  Perhaps the configuration should be run "inside" the package, with the User dictionary not on the dictionary path.

**Comment by mahrud** [comment] 2020-07-04 08:06
Duplicate of #1023

**Closed by mahrud** 2020-07-04 08:06 UTC
