### ISSUE TITLE
cmake wants GTEST_INCLUDE_DIR to be defined.

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#2017] opened 2021-04-01 16:37 UTC
a build failed here: https://github.com/Macaulay2/M2/pull/2016/checks?check_run_id=2240245363#step:8:150

**Comment by mahrud** [comment] 2021-04-01 20:35
No, it's optional.

**Comment by DanGrayson** [comment] 2021-04-01 20:47
Okay, but then why did the build fail?

**Comment by mahrud** [comment] 2021-04-01 21:07
I don't know. It passed [yesterday](https://github.com/Macaulay2/M2/runs/2236495571?check_suite_focus=true), so maybe it's a github actions issue.

Either way, cmake doesn't want latex.

**Comment by DanGrayson** [comment] 2021-04-01 23:14
Could this message signify the error?:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/Users/runner/work/M2/M2/M2/Macaulay2/e/GTEST_INCLUDE_DIR
   used as include directory in directory /Users/runner/work/M2/M2/M2/Macaulay2/e
```

**Comment by mahrud** [comment] 2021-04-02 00:12
If you want my help with this you should fix the issue to something more appropriate. This isn't about latex.

**Comment by DanGrayson** [comment] 2021-04-02 01:52
Sorry, I can't figure out what "fix the issue to something more appropriate" means.

**Comment by mahrud** [comment] 2021-04-04 17:03
Can you explain what is wrong?? I solved it for you, here: https://github.com/Macaulay2/M2/runs/2254827222?check_suite_focus=true

**Comment by DanGrayson** [comment] 2021-04-04 17:56
What's wrong is that a build failed and I don't know why.  I've changed the title to "cmake wants GTEST_INCLUDE_DIR to be defined", which is my latest guess about what is wrong.  (It's not about a test failing, as far as I can tell.  If you've changed something related to the definition of GTEST_INCLUDE_DIR, just let me know.)

**Comment by mahrud** [comment] 2021-04-04 18:09
Like I said, I fixed the problem which was caused by an update in github actions.

The nightly tests are failing only because _you_ decided to change the target of my pull request:
![image](https://user-images.githubusercontent.com/3147718/113517592-78b04780-9546-11eb-8ca1-0ef7a9569dd1.png)

Setting the target to the main branch was intended to fix the builds. I don't make mistakes like that.

I am informing you that this issue is now fixed in development, so merge development into main branch if you want builds to use my fix and please stop this ridiculous back and forth.

**Comment by DanGrayson** [comment] 2021-04-04 19:45
Ah, this change of yours is probably what you're referring to:

https://github.com/Macaulay2/M2/pull/2019/files#diff-9551b86860b16c6739f0bbc563490dc3111af22c94442638a5e5acd1ff03eb74

**Comment by DanGrayson** [comment] 2021-04-04 19:50
I'll keep this open until we can confirm the problem is fixed.

**Comment by DanGrayson** [comment] 2021-04-05 14:31
Closing, as the error did not occur in this build: https://github.com/Macaulay2/M2/actions/runs/717318419

**Closed** 2021-04-05 14:31 UTC
Labels: build system

**Comment by DanGrayson** [comment] 2021-04-05 14:34
> The nightly tests are failing only because _you_ decided to change the target of my pull request:
> ![image](https://user-images.githubusercontent.com/3147718/113517592-78b04780-9546-11eb-8ca1-0ef7a9569dd1.png)
> 
> Setting the target to the main branch was intended to fix the builds. I don't make mistakes like that.
> 


I pull all pull requests to `development`, so one more test build can be run before merging with `master` (on the branch `pre-master`).
