### ISSUE TITLE
Linking with static boost libraries with CMake

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1737] opened 2020-12-24 17:22 UTC
```
gallium$ cmake --build M2.git/M2/BUILD/build --target install-packages
ninja: error: '/usr/local/lib/libboost_regex-mt.dylib', needed by 'Macaulay2/e/libM2-engine.a', missing and no known rule to make it
gallium$ ls -l /usr/local/lib/libboost_regex-mt.*
lrwxrwxr-x  1 brew  admin      46 Nov 20 13:59 /usr/local/lib/libboost_regex-mt.a -> ../Cellar/boost/1.74.0/lib/libboost_regex-mt.a
```

**Comment by mahrud** [comment] 2020-12-24 19:08
The title of the issue is incorrect. If you build Boost locally with only static libraries, or if you use a distribution that doesn't come with shared libraries, you won't have this issue because then the `FindBoost.cmake` module that comes with Boost is also modified to use the static libraries. In other words, the cause of the error you got is that the installation of Boost was manually modified, but the `FindBoost.cmake` module was not changed accordingly, and broke it. So this isn't an issue of Macaulay2, or even CMake for that matter.

Also, Boost libraries are best not linked statically, because a lot of applications might use them, so it's efficient in many ways (e.g. see [here](https://www.boost.org/doc/libs/1_32_0/doc/html/bbv2/tutorial/linkage.html):
- smaller executable size (only one copy of the shared library needed on disk)
- hence also faster linkage
- smaller memory footage (only one copy of the shared library in memory)
- hence also faster loading of executables (because the shared library is already loaded)

This is why the static libraries of it are sometimes not even distributed (e.g. on Fedora). Still, if you insist on using static libraries, instead of deleting the shared library you should use:
```
cmake -U*Boost* -DBoost_USE_STATIC_LIBS=on .
```
to force using static libraries (see [here](https://cmake.org/cmake/help/latest/module/FindBoost.html) for more options). The `-U*Boost*` is there to unset Boost related variables first, so if this is the first time you run cmake, you can skip it.

I'll close this issue, but feel free to reopen if you have another suggestion.

**Comment by mahrud** [comment] 2020-12-24 19:09
@d-torrance might have more to add about static vs. dynamic linking. I'm fairly sure distributions don't like statically linked binaries.

**Comment by d-torrance** [comment] 2020-12-24 19:13
> @d-torrance might have more to add about static vs. dynamic linking. I'm fairly sure distributions don't like statically linked binaries.

That's correct -- Debian prefers dynamic linking.  See, e.g., https://wiki.debian.org/StaticLinking.

**Comment by DanGrayson** [comment] 2020-12-24 20:00
The "gatekeeper" of Apple's prefers distributed *.dmg files not to contain dynamic libraries, so we have to have a work-around.  One work-around would be to just use the autotools build, which I do.  Another, in the long run, would be to join homebrew so we don't need to make our own binary distributions.  Also, Mahrud's remarks about smaller executable sizes, while true, would apply only if we had more than one executable in our *.dmg file using the boost library, and that's not the case.

I'll try out Mahrud's suggestion, meanwhile.

**Comment by mahrud** [comment] 2020-12-24 20:07
> The "gatekeeper" of Apple's prefers distributed *.dmg files not to contain dynamic libraries, so we have to have a work-around.

Can the executables in the .dmg be linked against external dynamic libraries? We could mention that people should install boost using brew.

> Another, in the long run, would be to join homebrew so we don't need to make our own binary distributions.

Sure, #1166 is just waiting for dedicated people who would be willing to maintain a number of brew packages.

> Also, Mahrud's remarks about smaller executable sizes, while true, would apply only if we had more than one executable in our *.dmg file using the boost library, and that's not the case.

It's not just Macaulay2. There are other programs with executables that can use the same shared libraries. You might even have multiple versions of Macaulay2 installed in different prefixes, so it still applies.

**Comment by DanGrayson** [comment] 2020-12-24 20:20
> > The "gatekeeper" of Apple's prefers distributed *.dmg files not to contain dynamic libraries, so we have to have a work-around.
> 
> Can the executables in the .dmg be linked against external dynamic libraries? We could mention that people should install boost using brew.

I don't know, but probably yes.  The convention in the Mac world is that *.dmg files contain self-sufficient software, but our users perhaps could be imposed upon to install brew.  Mike might have an opinion about that.  @mikestillman 

> 
> > Another, in the long run, would be to join homebrew so we don't need to make our own binary distributions.
> 
> Sure, #1166 is just waiting for dedicated people who would be willing to maintain a number of brew packages.
> 
> > Also, Mahrud's remarks about smaller executable sizes, while true, would apply only if we had more than one executable in our *.dmg file using the boost library, and that's not the case.
> 
> It's not just Macaulay2. There are other programs with executables that can use the same shared libraries. 

There might be such other programs, but they wouldn't look inside `/Applications/Macaulay2-1.16` for shared libraries, so it's not relevant.

> You might even have multiple versions of Macaulay2 installed in different prefixes, so it still applies.

You might have that, but the M2 inside `/Applications/Macaulay2-1.15` would not look inside `/Applications/Macaulay2-1.16` for sharable libraries, so it doesn't really work.

**Comment by mahrud** [comment] 2020-12-24 20:25
> There might be such other programs, but they wouldn't look inside `/Applications/Macaulay2-1.16` for shared libraries, so it's not relevant.

I never suggested shipping the Boost shared libraries with Macaulay2. They will look where Boost's libraries are, presumably in `/usr/local/opt/lib`.

> You might have that, but the M2 inside `/Applications/Macaulay2-1.15` would not look inside `/Applications/Macaulay2-1.16` for sharable libraries, so it doesn't really work.

Same as above, the shared system libraries will be somewhere accessible by all of them. The reason why the previous title was so wrong is that when our CMake build builds a library like flint, it actually prefers static linking to dynamic linking, and you need to pass `-DBUILD_SHARED_LIBS=on` to use shared libraries for those instead. But for libraries that are found on the system, there is no reason to use static linking, because all builds can find those as well.

**Comment by DanGrayson** [comment] 2020-12-24 20:42
Okay, yes, but for the libraries under discussion, they are not found on the system, unless our users install brew.  Which might be a step we don't want to impose on them.  Let's see what Mike thinks of the idea.

**Comment by mikestillman** [comment] 2020-12-24 20:57
We cannot assume that our users have the boost libraries on their systems (and I really don't want to add another step to install M2, by making them have to install brew), so it seems we have two choices: include them statically, or place them with the other libraries we have to provide as well.  The gatekeeper thing on the mac is something that, I thought, @DanGrayson , that you thought we could not easily work around? Is there a chance we can get gatekeeper to work on the mac without us having to xattr the result?

**Comment by DanGrayson** [comment] 2020-12-24 21:22
> We cannot assume that our users have the boost libraries on their systems (and I really don't want to add another step to install M2, by making them have to install brew), so it seems we have two choices: include them statically, or place them with the other libraries we have to provide as well. The gatekeeper thing on the mac is something that, I thought, @DanGrayson , that you thought we could not easily work around? Is there a chance we can get gatekeeper to work on the mac without us having to xattr the result?

Yes, there's still a chance, but I dropped it after a week of frustration a year ago.  (The whole point of acceptance by the gatekeeper is so the user doesn't have to do `xattr`.)

**Closed** 2021-01-09 11:08 UTC
