### ISSUE TITLE
Repeated variable names

### ISSUE THREAD

**Issue by zteitler** [Macaulay2/M2#973] opened 2019-07-30 06:50 UTC
Repeating a variable name is allowed, but probably shouldn't be:

    R = ZZ[a,a];
    R_0 == R_1 -- false

Now all kinds of awkward things ensue like `R_0-R_1` being different from `0` or `R_1-R_0`, etc. It also happens this way:

    S = R[a];
    T = S[a];
    T_0 + S_0 - R_0 - R_1

Even if the "real" variables can be reached by `R_0`, `R_1`, etc., I think it still would be more clear to the user to give some kind of error message or warning, like how `ZZ[ideal]` is an error.

(I also tried `x = y -> y+1; R=ZZ[x]; (R_0) 3` but it didn't say 4, which would have been fun.)

**Comment by DanGrayson** [comment] 2019-07-30 12:57
I think it should be allowed, because when writing a function that receives a ring R as
a parameter, it should be possible to create R[x] in all cases, even if R involves the variable x.

**Comment by zteitler** [comment] 2019-07-30 14:43
Okay but what about R[x,x]?

**Comment by DanGrayson** [comment] 2019-07-30 15:10
A ring such as QQ[x,x] can result naturally from flattening a ring like R[x] when R involves x.

**Comment by zteitler** [comment] 2019-07-30 17:57
I see. Too bad that some confusion is possible but I see that it is difficult to avoid.

**Comment by mahrud** [comment] 2020-07-04 08:20
I'll close this as a duplicate of #1224, since that is an issue where even M2 gets confused about repeated variable names.

**Closed by mahrud** 2020-07-04 08:20 UTC
