### ISSUE TITLE
Is gftables necessary if we don't build factory?

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#375] opened 2016-03-13 23:53 UTC
Another question related to creating the Debian package:

Currently, the behavior of the M2 build system is to download gftables and install them in ${prefix}/share/Macaulay2/Core/factory/.  In Debian, however, downloading things during build is not allowed and using additional packages as build dependencies is preferred.

I'm trying to write a patch which will work for the Debian package but also keep the current behavior as default.

If I'm understanding the code correctly, it appears that M2 only does this so that the gftables are available to factory.  M2 doesn't use them directly.

However, if factory is already installed prior to building M2, then it seems as if gftables wouldn't be necessary at all, as factory should already know where they are.

I'm thinking that if BUILD_factory is no, then we should automatically set BUILD_gftables to no and skip the "setFactoryGFtableDirectory gfdir" line in factor.m2.

Am I understanding this correctly?  Thanks!

**Comment by d-torrance** [comment] 2016-03-13 23:56
This may essentially be a duplicate of https://github.com/Macaulay2/M2/issues/295.

**Comment by d-torrance** [comment] 2016-03-14 01:26
After reading a bit more, it looks like gftables as a separate entity from factory is completely unnecessary since the release of singular 4-0-0.  I've submitted #376 to get rid of it.

**Comment by DanGrayson** [comment] 2016-03-14 12:54
I think this is not a duplicate of #295 -- it's concerned with what happens when M2 builds factory.

Our configure script always sets gftables to be built, but you are right -- if factory is installed correctly,
it can find the gftables.

**Closed** 2016-03-20 16:32 UTC
