### ISSUE TITLE
release-1.16 memtailor git submodule init fails with "fatal: reference is not a tree"

### ISSUE THREAD

**Issue by omsai** [Macaulay2/M2#1382] opened 2020-07-08 22:21 UTC
Getting decently far along in the compilation process, but fails with:

```
fatal: reference is not a tree: 31024178b1337c364b6f652e3de0d893d5874223
Unable to checkout '31024178b1337c364b6f652e3de0d893d5874223' in submodule path 'M2/submodules/memtailor'
```

Here is a little more context from the `make` output:

```
...
libzsolve.so.0
libzsolve.so.0.0.0
make[1]: Leaving directory '/shared/admin/sw-src/rhel6/macaulay2/M2/M2/libraries'
cd ./.. && git submodule update --init M2/submodules/memtailor
Submodule 'M2/submodules/memtailor' (https://github.com/Macaulay2/memtailor) registered for path 'M2/submodules/memtailor'
Initialized empty Git repository in /shared/admin/sw-src/rhel6/macaulay2/M2/M2/submodules/memtailor/.git/
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 290 (delta 22), reused 30 (delta 8), pack-reused 241
Receiving objects: 100% (290/290), 85.89 KiB, done.
Resolving deltas: 100% (133/133), done.
fatal: reference is not a tree: 31024178b1337c364b6f652e3de0d893d5874223
Unable to checkout '31024178b1337c364b6f652e3de0d893d5874223' in submodule path 'M2/submodules/memtailor'
make: *** [GNUmakefile:200: submodules/memtailor/configure.ac] Error 1
make: Leaving directory '/shared/admin/sw-src/rhel6/macaulay2/M2/M2'
```

StackOverflow suggests this type of submodule issue may be something you folks need to look at: https://stackoverflow.com/q/13425298

**Comment by DanGrayson** [comment] 2020-07-09 00:56
I can't reproduce your problem here:
```sh
einsteinium$ cd /tmp
einsteinium$ git clone git@github.com:Macaulay2/M2.git
Cloning into 'M2'...
remote: Enumerating objects: 76, done.        
remote: Counting objects: 100% (76/76), done.        
remote: Compressing objects: 100% (64/64), done.        
remote: Total 193357 (delta 30), reused 25 (delta 11), pack-reused 193281        
Receiving objects: 100% (193357/193357), 55.15 MiB | 1.88 MiB/s, done.
Resolving deltas: 100% (139876/139876), done.
Updating files: 100% (4614/4614), done.
einsteinium$ cd M2/
einsteinium$ git submodule update --init M2/submodules/memtailor 
Submodule 'M2/submodules/memtailor' (https://github.com/Macaulay2/memtailor) registered for path 'M2/submodules/memtailor'
Cloning into '/private/tmp/M2/M2/submodules/memtailor'...
remote: Enumerating objects: 5, done.        
remote: Counting objects: 100% (5/5), done.        
remote: Compressing objects: 100% (1/1), done.        
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0        
Unpacking objects: 100% (3/3), 1.02 KiB | 347.00 KiB/s, done.
From https://github.com/Macaulay2/memtailor
 * branch            31024178b1337c364b6f652e3de0d893d5874223 -> FETCH_HEAD
Submodule path 'M2/submodules/memtailor': checked out '31024178b1337c364b6f652e3de0d893d5874223'
einsteinium$ 
```

**Comment by DanGrayson** [comment] 2020-07-09 00:59
Maybe you could try what I tried above.

**Comment by omsai** [comment] 2020-07-09 01:03
Ah, though it looks like you're using the master branch and not the release-1.16 branch mentioned in the issue title?

**Comment by DanGrayson** [comment] 2020-07-09 01:09
Oops, missed that.  Still, same result at my end:
```bash
$ git clone git@github.com:Macaulay2/M2.git
Cloning into 'M2'...
remote: Enumerating objects: 76, done.        
remote: Counting objects: 100% (76/76), done.        
remote: Compressing objects: 100% (64/64), done.        
remote: Total 193357 (delta 30), reused 25 (delta 11), pack-reused 193281        
Receiving objects: 100% (193357/193357), 55.15 MiB | 1.41 MiB/s, done.
Resolving deltas: 100% (139876/139876), done.
Updating files: 100% (4614/4614), done.
$ cd M2
$ git checkout release-1.16
Branch 'release-1.16' set up to track remote branch 'release-1.16' from 'origin'.
Switched to a new branch 'release-1.16'
$ git submodule update --init M2/submodules/memtailor 
Submodule 'M2/submodules/memtailor' (https://github.com/Macaulay2/memtailor) registered for path 'M2/submodules/memtailor'
Cloning into '/private/tmp/M2/M2/submodules/memtailor'...
remote: Enumerating objects: 5, done.        
remote: Counting objects: 100% (5/5), done.        
remote: Compressing objects: 100% (1/1), done.        
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0        
Unpacking objects: 100% (3/3), 1.02 KiB | 521.00 KiB/s, done.
From https://github.com/Macaulay2/memtailor
 * branch            31024178b1337c364b6f652e3de0d893d5874223 -> FETCH_HEAD
Submodule path 'M2/submodules/memtailor': checked out '31024178b1337c364b6f652e3de0d893d5874223'
```

Maybe try these commands at your end.

**Comment by DanGrayson** [comment] 2020-07-09 01:42
Try `git submodule sync`

**Comment by mahrud** [comment] 2020-07-09 07:20
That commit is not on any of the branches of Macaulay2/memtailor because the PR that adds that commit hasn't been merged yet: https://github.com/Macaulay2/memtailor/pull/6
cc: @mikestillman

**Comment by DanGrayson** [comment] 2020-07-09 11:56
Mahrud, you're right about that, but then why did my test above succeed?  It seems to be a contradiction.

**Comment by mahrud** [comment] 2020-07-09 12:13
I wondered that, too. Maybe different versions of git?

**Comment by DanGrayson** [comment] 2020-07-09 12:34
It works here with git 2.17.1 and 2.27.0.  @omsai  -- what version of git are you running?

By the way, `git submodule sync` is not going to help, since we've used only one URL for memtailor.

@omsai -- could you duplicate the simple test I conducted?

**Comment by DanGrayson** [comment] 2020-07-09 12:38
If it's RHEL6, that's too old (RHEL7 came out in 2014).  I've tried to build M2 on RHEL6 at gatech and gave up.

**Comment by omsai** [comment] 2020-07-09 12:39
@DanGrayson I'm using an ancient version on RHEL 6:

```console
$ git --version
git version 1.7.1
```

I had compiled a newer version compiled as a module:

```console
$ module -t avail git |& grep ^git
git/2.7.2
gitlfs/2.10.0
```

... but it sounds like I should probably compile the git latest version.

**Comment by DanGrayson** [comment] 2020-07-09 12:43
Mahrud, the commits contained in a pull request seem to be contained in the repository at github:

```
$ git clone git@github.com:Macaulay2/memtailor
Cloning into 'memtailor'...
remote: Enumerating objects: 49, done.        
remote: Counting objects: 100% (49/49), done.        
remote: Compressing objects: 100% (40/40), done.        
remote: Total 290 (delta 22), reused 30 (delta 8), pack-reused 241        
Receiving objects: 100% (290/290), 85.89 KiB | 1.83 MiB/s, done.
Resolving deltas: 100% (133/133), done.

$ cd memtailor

$ git fetch origin 31024178b1337c364b6f652e3de0d893d5874223
remote: Enumerating objects: 5, done.        
remote: Counting objects: 100% (5/5), done.        
remote: Compressing objects: 100% (1/1), done.        
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0        
Unpacking objects: 100% (3/3), done.
From github.com:Macaulay2/memtailor
 * branch            31024178b1337c364b6f652e3de0d893d5874223 -> FETCH_HEAD
```

It makes sense, since github has to do merges and diffs.

**Comment by omsai** [comment] 2020-07-09 12:43
> If it's RHEL6, that's too old (RHEL7 came out in 2014). I've tried to build M2 on RHEL6 at gatech and gave up.

Haha, we've had several hours of fun and games getting as far as we have compiling on RHEL6.  I should show the the size of our help desk ticket.  But I think it's doable.  On the spectrum of build errors we've had to deal with compiling research software, Macaulay2 is still very much in my "well written" software category.

**Comment by DanGrayson** [comment] 2020-07-09 12:57
Thanks!

But my memory is faulty, I did succeed building it on RHEL6.7 on about April 10, with the modules below.  Maybe I was remembering the frustration more than the final success. 


Okay, I've just reproduced your error with git 1.7.1 and found that git 2.13.4 succeeds!


```
module purge
module load -f make/4.3
module load -f yasm/1.3.0
module load -f automake/1.15
module load -f gcc/4.9.0
module load -f libtool/2.4.3
module load -f autoconf/2.69
module load -f git/2.13.4
```

**Comment by omsai** [comment] 2020-07-09 13:53
Here's my list now:

```console
$ module list -t
Currently Loaded Modulefiles:
lzma/4.32.7
eigen/3.3.4
pre-module
post-module
m4/1.4.17
make/4.3
autoconf/2.69
gcc/9.2.0
boost/1.66.0
sage/8.0
automake/1.16
pkg-config/0.29.1
libtool/2.4.6
git/2.27.0
```

Once I  confirm I get past the error on my end I'll close the issue or let you all know if I still have trouble.

**Comment by mahrud** [comment] 2020-07-09 13:55
Dan, wouldn't it be easier to merge the pull requests? They are all pretty
reasonable fixes.

**Comment by omsai** [comment] 2020-07-09 13:58
All's well now; thanks a million.

```console
[maf15122admin@cn01 M2]$ ls
bugs  M2  README
[maf15122admin@cn01 M2]$ git submodule sync
Synchronizing submodule url for 'M2/Macaulay2/editors/emacs'
Synchronizing submodule url for 'M2/submodules/bdwgc'
Synchronizing submodule url for 'M2/submodules/fflas_ffpack'
Synchronizing submodule url for 'M2/submodules/flint2'
Synchronizing submodule url for 'M2/submodules/frobby'
Synchronizing submodule url for 'M2/submodules/givaro'
Synchronizing submodule url for 'M2/submodules/googletest'
Synchronizing submodule url for 'M2/submodules/libatomic_ops'
Synchronizing submodule url for 'M2/submodules/mathic'
Synchronizing submodule url for 'M2/submodules/mathicgb'
Synchronizing submodule url for 'M2/submodules/memtailor'
Synchronizing submodule url for 'M2/submodules/mpir'
[maf15122admin@cn01 M2]$ git submodule update --init --recursive                                                                                   
Cloning into '/shared/admin/sw-src/rhel6/macaulay2/M2/M2/submodules/fflas_ffpack'...
Cloning into '/shared/admin/sw-src/rhel6/macaulay2/M2/M2/submodules/flint2'...
Cloning into '/shared/admin/sw-src/rhel6/macaulay2/M2/M2/submodules/frobby'...
Cloning into '/shared/admin/sw-src/rhel6/macaulay2/M2/M2/submodules/givaro'...
Cloning into '/shared/admin/sw-src/rhel6/macaulay2/M2/M2/submodules/googletest'...
Cloning into '/shared/admin/sw-src/rhel6/macaulay2/M2/M2/submodules/libatomic_ops'...
Cloning into '/shared/admin/sw-src/rhel6/macaulay2/M2/M2/submodules/mathic'...
Cloning into '/shared/admin/sw-src/rhel6/macaulay2/M2/M2/submodules/mathicgb'...
Cloning into '/shared/admin/sw-src/rhel6/macaulay2/M2/M2/submodules/mpir'...
remote: Enumerating objects: 3143, done.
remote: Counting objects: 100% (3143/3143), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 8995 (delta 3101), reused 3122 (delta 3083), pack-reused 5852
Receiving objects: 100% (8995/8995), 6.13 MiB | 3.34 MiB/s, done.
Resolving deltas: 100% (6783/6783), completed with 244 local objects.
From https://github.com/Macaulay2/bdwgc
 * branch              98ac50b6311219b8f57a794deb9a72d2a25b23ce -> FETCH_HEAD
Submodule path 'M2/submodules/bdwgc': checked out '98ac50b6311219b8f57a794deb9a72d2a25b23ce'
Submodule path 'M2/submodules/fflas_ffpack': checked out '23928f90cad1c2e96a868a737606fea0191307a1'
Submodule path 'M2/submodules/flint2': checked out 'fe1853f781c4a922bfb78568f21ae59de9efbdd4'
Submodule path 'M2/submodules/frobby': checked out 'd12b7b786a0e50765c1a2878601125ac2f55b68c'
Submodule path 'M2/submodules/givaro': checked out 'e890ae4c06d7420140b98d42c8b69d3854458779'
Submodule path 'M2/submodules/googletest': checked out '703bd9caab50b139428cea1aaff9974ebee5742e'
Submodule path 'M2/submodules/libatomic_ops': checked out 'ba6c3170412ef7f751ff63e2b656296265dcff93'
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 16 (delta 13), reused 15 (delta 12), pack-reused 0
Unpacking objects: 100% (16/16), 2.83 KiB | 55.00 KiB/s, done.
From https://github.com/Macaulay2/mathic
 * branch            d26913a8117c2c2191d286ae766592a84ec4d003 -> FETCH_HEAD
Submodule path 'M2/submodules/mathic': checked out 'd26913a8117c2c2191d286ae766592a84ec4d003'
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 11 (delta 9), reused 11 (delta 9), pack-reused 0
Unpacking objects: 100% (11/11), 2.40 KiB | 70.00 KiB/s, done.
From https://github.com/Macaulay2/mathicgb
 * branch            d8dd3d617e7c5658d3222490c1d8d8984a848c0b -> FETCH_HEAD
Submodule path 'M2/submodules/mathicgb': checked out 'd8dd3d617e7c5658d3222490c1d8d8984a848c0b'
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), 1.02 KiB | 130.00 KiB/s, done.
From https://github.com/Macaulay2/memtailor
 * branch            31024178b1337c364b6f652e3de0d893d5874223 -> FETCH_HEAD
Submodule path 'M2/submodules/memtailor': checked out '31024178b1337c364b6f652e3de0d893d5874223'
Submodule path 'M2/submodules/mpir': checked out '82816d99518e8779cbe981e6667a9b0fd23be20a'
[maf15122admin@cn01 M2]$ git submodule update --init --recursive
[maf15122admin@cn01 M2]$ git status
On branch release-1.16
Your branch is up to date with 'origin/release-1.16'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        M2/Macaulay2/packages/Makefile
        M2/Macaulay2/tests/threads/Makefile
        M2/libraries/mpsolve/Makefile

nothing added to commit but untracked files present (use "git add" to track)
[maf15122admin@cn01 M2]$ git log --oneline -1
3c2eac5a4 (HEAD -> release-1.16, origin/release-1.16) fix the makefile for 4ti2
```

**Closed** 2020-07-09 13:59 UTC
Labels: build system

**Comment by DanGrayson** [comment] 2020-07-09 14:38
> Dan, wouldn't it be easier to merge the pull requests? They are all pretty reasonable fixes.

Maybe, but I'm not an author of any of those three repositories, so you'll have to wait for @mikestillman .

**Comment by mikestillman** [comment] 2020-07-09 15:46
Sorry, I hand't noticed that there was a pending request.  I'll take a look at it.
