### ISSUE TITLE
Dmodules package can't run 4ti2 program

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1449] opened 2020-07-31 11:49 UTC
The Dmodules package can't run 4ti2 program, on Ubuntu 20.04 and on Fedora 32:

```m2
-- -*- M2-comint -*- hash: 1344483513

i1 : A = matrix{{1,1,1},{0,1,2}}

o1 = | 1 1 1 |
     | 0 1 2 |

              2        3
o1 : Matrix ZZ  <--- ZZ

i2 : b = {3,4}

o2 = {3, 4}

o2 : List

i3 : I = gkz (A,b)
sh: /home/dan/src/M2/M2/BUILD/dan/builds.tmp/fedora-1425/usr-dist/x86_64-Linux-fedora-32/libexec/Macaulay2/bin/markov: No such file or directory
stdio:3:5:(3): error: error occurred while executing external program 4ti2: markov
```

We didn't build it, so it should be looking in the secret place, either /usr/lib64/4ti2/bin/markov or  /usr/bin/4ti2-markov.

@d-torrance

**Comment by d-torrance** [comment] 2020-07-31 12:00
The problem is that 93dfe83, which checks for 4ti2 during `configure`, has already been merged as part of #1413, but #1400, which actually adds `findProgram`/`runProgram` support for the 4ti2, is still pending review by the package authors.

I should have included that commit as part of that PR!  I'll submit a new PR reverting that commit, and then tack it on to #1400.

**Closed** 2020-08-01 15:01 UTC
